"""Tests for hame.trg_plan_repealed.

When a plan gets the repealed lifecycle status, the trigger sets the same status
and end date on its plan objects, regulations and propositions, the way Ryhti
does. The trigger is generated by generate_plan_repealed_triggers in
database/triggers.py.
"""

from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING

import pytest
import sqlalchemy

from database import codes, models
from test.conftest import yesterday

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


@pytest.fixture
def regulation_group(
    session: Session,
    cancelled_plan: models.Plan,
    valid_status_instance: codes.LifeCycleStatus,
    type_of_plan_regulation_group_instance: codes.TypeOfPlanRegulationGroup,
    type_of_plan_regulation_instance: codes.TypeOfPlanRegulation,
) -> models.PlanRegulationGroup:
    """A regulation group of the cancelled plan with one regulation and one proposition."""
    group = models.PlanRegulationGroup(
        short_name="R",
        plan=cancelled_plan,
        ordering=1,
        type_of_plan_regulation_group=type_of_plan_regulation_group_instance,
        name={"fin": "test_regulation_group"},
    )
    group.plan_regulations = [
        models.PlanRegulation(
            lifecycle_status=valid_status_instance,
            type_of_plan_regulation=type_of_plan_regulation_instance,
            ordering=1,
            period_of_validity_start=yesterday(),
        )
    ]
    group.plan_propositions = [
        models.PlanProposition(
            lifecycle_status=valid_status_instance,
            text_value={"fin": "test_proposition"},
            ordering=1,
            period_of_validity_start=yesterday(),
        )
    ]
    session.add(group)
    session.commit()
    return group


def children(
    session: Session, plan: models.Plan
) -> list[models.PlanObjectBase | models.PlanRegulation | models.PlanProposition]:
    """The plan objects, regulations and propositions of the plan, read back."""
    session.refresh(plan)
    rows: list[models.PlanObjectBase | models.PlanRegulation | models.PlanProposition]
    rows = [*plan.land_use_areas, *plan.other_areas, *plan.lines, *plan.points]
    for table in (models.PlanRegulation, models.PlanProposition):
        rows.extend(
            session.scalars(
                sqlalchemy.select(table)
                .join(table.plan_regulation_group)
                .where(models.PlanRegulationGroup.plan_id == plan.id)
            )
        )
    for row in rows:
        session.refresh(row)
    return rows


def repeal(
    session: Session, plan: models.Plan, repealed_status: codes.LifeCycleStatus
) -> None:
    plan.lifecycle_status = repealed_status
    plan.period_of_validity_end = yesterday()
    session.commit()


def test_repealed_plan_repeals_its_children(
    session: Session,
    cancelled_plan: models.Plan,
    regulation_group: models.PlanRegulationGroup,  # noqa: ARG001  # adds regulations
    repealed_status_instance: codes.LifeCycleStatus,
) -> None:
    repeal(session, cancelled_plan, repealed_status_instance)

    rows = children(session, cancelled_plan)
    assert len(rows) == 7  # 5 plan objects, 1 regulation, 1 proposition
    for row in rows:
        assert row.lifecycle_status.value == "14"
        assert row.period_of_validity_end == yesterday()


def test_already_repealed_child_keeps_its_end_date(
    session: Session,
    cancelled_plan: models.Plan,
    repealed_status_instance: codes.LifeCycleStatus,
) -> None:
    earlier = yesterday() - timedelta(days=10)
    line = cancelled_plan.lines[0]
    line.lifecycle_status = repealed_status_instance
    line.period_of_validity_end = earlier
    session.commit()

    repeal(session, cancelled_plan, repealed_status_instance)

    session.refresh(line)
    assert line.lifecycle_status.value == "14"
    assert line.period_of_validity_end == earlier


def test_child_with_an_earlier_end_date_keeps_it(
    session: Session,
    cancelled_plan: models.Plan,
    repealed_status_instance: codes.LifeCycleStatus,
) -> None:
    earlier = yesterday() - timedelta(days=10)
    point = cancelled_plan.points[0]
    point.period_of_validity_end = earlier
    session.commit()

    repeal(session, cancelled_plan, repealed_status_instance)

    session.refresh(point)
    assert point.lifecycle_status.value == "14"
    assert point.period_of_validity_end == earlier


def test_other_status_changes_leave_the_children_alone(
    session: Session,
    cancelled_plan: models.Plan,
    regulation_group: models.PlanRegulationGroup,  # noqa: ARG001  # adds regulations
    preparation_status_instance: codes.LifeCycleStatus,
) -> None:
    cancelled_plan.lifecycle_status = preparation_status_instance
    cancelled_plan.period_of_validity_end = yesterday()
    session.commit()

    for row in children(session, cancelled_plan):
        assert row.lifecycle_status.value == "13"
        assert row.period_of_validity_end is None
