"""Tests for the triggers that fill the plan cancellation info tables.

A plan of a plan matter marked repealing repeals every valid plan of the same
level 1 plan type that it overlaps. The triggers are generated by
generate_plan_cancellation_info_triggers in database/triggers.py and use
hame.repealed_plans and hame.repealed_plan_objects in database/functions.py.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

import pytest
import sqlalchemy
from geoalchemy2.shape import to_shape

from database import codes, models
from test.conftest import MIDDLE, SIDE, area, line

if TYPE_CHECKING:
    from shapely.geometry.base import BaseGeometry
    from sqlalchemy.orm import Session


def cancellation_infos(
    session: Session, plan: models.Plan
) -> list[models.PlanCancellationInfo]:
    """The cancellation infos the plan issues, read back from the database."""
    return list(
        session.scalars(
            sqlalchemy.select(models.PlanCancellationInfo)
            .where(models.PlanCancellationInfo.plan_id == plan.id)
            .order_by(models.PlanCancellationInfo.cancelled_plan_id)
        )
    )


def repealed_objects(
    session: Session, info: models.PlanCancellationInfo
) -> dict[str, models.PlanObjectCancellationInfo]:
    """The plan object cancellation infos, by the id of the repealed object."""
    rows = session.scalars(
        sqlalchemy.select(models.PlanObjectCancellationInfo).where(
            models.PlanObjectCancellationInfo.plan_cancellation_info_id == info.id
        )
    )
    return {
        str(row.land_use_area_id or row.other_area_id or row.line_id or row.point_id): (
            row
        )
        for row in rows
    }


def named(plan: models.Plan, name: str) -> models.PlanObjectBase:
    """Look up a plan object of the plan by its Finnish name."""
    objects: list[models.PlanObjectBase] = [
        *plan.land_use_areas,
        *plan.lines,
        *plan.points,
    ]
    return next(o for o in objects if o.name is not None and o.name["fin"] == name)


def remaining(row: models.PlanObjectCancellationInfo) -> BaseGeometry:
    """The geometry that stays valid, whichever geometry column holds it."""
    geom = (
        row.remaining_valid_geom_polygon
        or row.remaining_valid_geom_line
        or row.remaining_valid_geom_point
    )
    # Exactly one of the columns is set, see
    # ck_plan_object_cancellation_info_remaining_valid_geom.
    assert geom is not None
    return to_shape(geom)


def test_no_cancellation_info_without_the_repealing_flag(
    session: Session,
    another_plan_matter_instance: models.PlanMatter,
    cancelled_plan: models.Plan,
    preparation_status_instance: codes.LifeCycleStatus,
) -> None:
    """A plan of a plan matter that is not repealing repeals nothing."""
    plan = models.Plan(
        id=str(uuid.uuid4()),
        plan_matter=another_plan_matter_instance,
        name={"fin": "Tavallinen kaava"},
        geom=area(0, 0, SIDE, SIDE),
        lifecycle_status=preparation_status_instance,
    )
    session.add(plan)
    session.commit()

    assert cancellation_infos(session, plan) == []
    assert cancelled_plan.id is not None


def test_partly_covered_plan_repeals_the_plan_objects(
    session: Session, repealing_plan: models.Plan, cancelled_plan: models.Plan
) -> None:
    """A plan the repealing plan only partly covers is repealed by its objects."""
    infos = cancellation_infos(session, repealing_plan)

    assert len(infos) == 1
    assert infos[0].cancelled_plan_id == cancelled_plan.id
    assert infos[0].cancels_entire_plan is False

    objects = repealed_objects(session, infos[0])
    expected = {
        named(cancelled_plan, name).id
        for name in ("covered_area", "split_area", "split_line", "covered_point")
    }
    assert set(objects) == expected


@pytest.mark.parametrize("name", ["covered_area", "covered_point"])
def test_covered_plan_object_is_repealed_entirely(
    session: Session,
    repealing_plan: models.Plan,
    cancelled_plan: models.Plan,
    name: str,
) -> None:
    """A plan object inside the repealing plan leaves no geometry valid."""
    info = cancellation_infos(session, repealing_plan)[0]
    row = repealed_objects(session, info)[named(cancelled_plan, name).id]

    assert row.cancels_entire_plan_object is True
    assert row.remaining_valid_geom_polygon is None
    assert row.remaining_valid_geom_line is None
    assert row.remaining_valid_geom_point is None


def test_split_area_keeps_the_part_outside_the_repealing_plan(
    session: Session, repealing_plan: models.Plan, cancelled_plan: models.Plan
) -> None:
    """The eastern half of the area stays valid."""
    info = cancellation_infos(session, repealing_plan)[0]
    row = repealed_objects(session, info)[named(cancelled_plan, "split_area").id]

    assert row.cancels_entire_plan_object is False
    assert row.remaining_valid_geom_line is None
    assert row.remaining_valid_geom_point is None
    assert remaining(row).equals(to_shape(area(MIDDLE, 10, 60, 30)))


def test_split_line_keeps_the_part_outside_the_repealing_plan(
    session: Session, repealing_plan: models.Plan, cancelled_plan: models.Plan
) -> None:
    """The eastern half of the line stays valid, in the line geometry column."""
    info = cancellation_infos(session, repealing_plan)[0]
    row = repealed_objects(session, info)[named(cancelled_plan, "split_line").id]

    assert row.cancels_entire_plan_object is False
    assert row.remaining_valid_geom_polygon is None
    assert row.remaining_valid_geom_point is None
    assert remaining(row).equals(to_shape(line(MIDDLE, 50, 60, 50)))


def test_entirely_covered_plan_has_no_plan_object_rows(
    session: Session, repealing_plan: models.Plan
) -> None:
    """Ryhti allows no plan object cancellation infos on a whole plan."""
    repealing_plan.geom = area(0, 0, SIDE, SIDE)
    session.commit()

    infos = cancellation_infos(session, repealing_plan)

    assert len(infos) == 1
    assert infos[0].cancels_entire_plan is True
    assert repealed_objects(session, infos[0]) == {}


def test_only_touching_plan_is_not_repealed(
    session: Session, repealing_plan: models.Plan
) -> None:
    """A plan that shares only a border with the repealing plan stays valid."""
    repealing_plan.geom = area(SIDE, 0, SIDE + MIDDLE, SIDE)
    session.commit()

    assert cancellation_infos(session, repealing_plan) == []


def test_plan_of_another_level_1_plan_type_is_not_repealed(
    session: Session,
    repealing_plan: models.Plan,
    repealing_plan_matter: models.PlanMatter,
) -> None:
    """A repealing plan only repeals plans of its own level 1 plan type."""
    repealing_plan_matter.plan_type = codes.PlanType(value="3", level=1, status="LOCAL")
    session.commit()
    # The plan matter carries the plan type, so the plan is written again to
    # make the trigger read it.
    repealing_plan.geom = area(0, 0, MIDDLE, SIDE - 1)
    session.commit()

    assert cancellation_infos(session, repealing_plan) == []


def test_plan_of_the_same_plan_matter_is_not_repealed(
    session: Session,
    cancelled_plan: models.Plan,
    plan_matter_instance: models.PlanMatter,
    preparation_status_instance: codes.LifeCycleStatus,
) -> None:
    """A plan does not repeal the earlier phases of its own plan matter."""
    plan_matter_instance.repealing = True
    session.commit()

    plan = models.Plan(
        id=str(uuid.uuid4()),
        plan_matter=plan_matter_instance,
        name={"fin": "Saman kaava-asian kaava"},
        geom=area(0, 0, MIDDLE, SIDE),
        lifecycle_status=preparation_status_instance,
    )
    session.add(plan)
    session.commit()

    assert cancellation_infos(session, plan) == []
    assert cancelled_plan.id is not None


def test_plan_that_is_not_final_is_not_repealed(
    session: Session, repealing_plan: models.Plan, cancelled_plan: models.Plan
) -> None:
    """Only the plans of hame.plan_valid are repealed."""
    cancelled_plan.final = False
    session.commit()
    repealing_plan.geom = area(0, 0, MIDDLE, SIDE - 1)
    session.commit()

    assert cancellation_infos(session, repealing_plan) == []


def test_repealing_flag_fills_and_clears_the_cancellation_info(
    session: Session,
    repealing_plan: models.Plan,
    repealing_plan_matter: models.PlanMatter,
) -> None:
    """Unsetting the flag on the plan matter removes the rows again."""
    assert len(cancellation_infos(session, repealing_plan)) == 1

    repealing_plan_matter.repealing = False
    session.commit()

    assert cancellation_infos(session, repealing_plan) == []

    repealing_plan_matter.repealing = True
    session.commit()

    assert len(cancellation_infos(session, repealing_plan)) == 1


def test_moving_the_repealing_plan_away_clears_the_cancellation_info(
    session: Session, repealing_plan: models.Plan
) -> None:
    repealing_plan.geom = area(2 * SIDE, 0, 3 * SIDE, SIDE)
    session.commit()

    assert cancellation_infos(session, repealing_plan) == []


def test_plan_that_stays_repealed_keeps_its_cancellation_info_id(
    session: Session, repealing_plan: models.Plan
) -> None:
    """The rows are upserted, so rows added under them by hand survive."""
    original_id = cancellation_infos(session, repealing_plan)[0].id

    repealing_plan.geom = area(0, 0, MIDDLE, SIDE - 1)
    session.commit()

    assert cancellation_infos(session, repealing_plan)[0].id == original_id
