from __future__ import annotations

from collections.abc import Generator
from typing import TYPE_CHECKING

import alembic
import psycopg
import pytest
from psycopg.sql import SQL, Identifier, Literal

from database.db_helper import UserCredentials
from database.models import Base
from database.views import views
from lambdas.db_manager import db_manager

if TYPE_CHECKING:
    from alembic.config import Config
    from psycopg import Connection
    from psycopg.rows import TupleRow

    from database.db_helper import ConnectionParameters

ROLE_READ_ONLY = "arho_read_only"
ROLE_READ_WRITE = "arho_read_write"
ROLE_ADMIN = "arho_admin"

arho_roles = {ROLE_READ_ONLY, ROLE_READ_WRITE}


@pytest.fixture(scope="module")
def db_connection(
    main_db_params: ConnectionParameters,
) -> Generator[Connection[TupleRow]]:
    with psycopg.connect(**main_db_params) as conn:
        yield conn


def test_database_is_migrated_to_the_latest_revision(
    db_connection: Connection, current_head_version_id: str
) -> None:
    with db_connection.cursor() as cur:
        cur.execute("SELECT version_num FROM alembic_version")
        assert cur.fetchone() == (current_head_version_id,)


def test_database_migrations_are_up_to_date(alembic_cfg: Config) -> None:
    try:
        alembic.command.check(alembic_cfg)
    except alembic.util.AutogenerateDiffsDetected:
        pytest.fail("Database migrations are not up to date")


def test_schemas_exists(db_connection: Connection) -> None:
    with db_connection.cursor() as cur:
        cur.execute(
            "SELECT schema_name FROM information_schema.schemata "
            "WHERE schema_name IN ('hame', 'codes') ORDER BY schema_name DESC"
        )
        assert cur.fetchall() == [("hame",), ("codes",)]


def test_roles_exist(db_connection: Connection) -> None:
    with db_connection.cursor() as cur:
        cur.execute("SELECT rolname FROM pg_roles")
        assert set(arho_roles).issubset({row[0] for row in cur.fetchall()})


@pytest.mark.parametrize("user", [ROLE_READ_ONLY, ROLE_READ_WRITE])
def test_database_privileges(db_connection: Connection, user: str) -> None:
    cur = db_connection.execute(
        "SELECT has_database_privilege(%s, 'hame', 'connect')", (user,)
    )
    assert cur.fetchone() == (True,)


@pytest.mark.parametrize("user", [ROLE_READ_ONLY, ROLE_READ_WRITE])
@pytest.mark.parametrize("schema", ["hame", "codes"])
def test_schema_privileges(db_connection: Connection, user: str, schema: str) -> None:
    with db_connection.cursor() as cur:
        cur.execute("SELECT has_schema_privilege(%s, %s, 'usage')", (user, schema))
        assert cur.fetchone() == (True,)


def hame_tables() -> set[str]:
    t = {
        table.name for table in Base.metadata.tables.values() if table.schema == "hame"
    }
    t.update(v.signature for v in views if v.schema == "hame")

    return t


def code_tables() -> set[str]:
    return {
        table.name for table in Base.metadata.tables.values() if table.schema == "codes"
    }


@pytest.mark.parametrize("table_name", hame_tables())
def test_hame_tables_exists(db_connection: Connection, table_name: str) -> None:
    with db_connection.cursor() as cur:
        cur.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema='hame' AND table_name=%s",
            (table_name,),
        )
        assert cur.fetchone() == (table_name,)


@pytest.mark.parametrize("table_name", code_tables())
def test_code_tables_exists(db_connection: Connection, table_name: str) -> None:
    with db_connection.cursor() as cur:
        cur.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema='codes' AND table_name=%s",
            (table_name,),
        )
        assert cur.fetchone() == (table_name,)


def table_privileges(
    db_connection: Connection, schema: str, table: str, role: str
) -> set[str]:
    cur = db_connection.execute(
        "SELECT privilege_type "
        "FROM information_schema.role_table_grants "
        "WHERE "
        "  table_schema = %s "
        "  AND table_name = %s "
        "  AND grantee = %s",
        (schema, table, role),
    )
    return {row[0] for row in cur}


@pytest.mark.parametrize("table_name", hame_tables())
def test_read_only_role_privileges_on_hame_tables(
    db_connection: Connection, table_name: str
) -> None:
    privileges = table_privileges(db_connection, "hame", table_name, ROLE_READ_ONLY)
    assert "SELECT" in privileges
    assert "INSERT" not in privileges
    assert "UPDATE" not in privileges
    assert "DELETE" not in privileges


@pytest.mark.parametrize("table_name", code_tables())
def test_read_only_role_privileges_on_code_tables(
    db_connection: Connection, table_name: str
) -> None:
    privileges = table_privileges(db_connection, "codes", table_name, ROLE_READ_ONLY)
    assert "SELECT" in privileges
    assert "INSERT" not in privileges
    assert "UPDATE" not in privileges
    assert "DELETE" not in privileges


@pytest.mark.parametrize("table_name", hame_tables())
def test_read_write_role_privileges_on_hame_tables(
    db_connection: Connection, table_name: str
) -> None:
    privileges = table_privileges(db_connection, "hame", table_name, ROLE_READ_WRITE)
    assert "SELECT" in privileges
    assert "INSERT" in privileges
    assert "UPDATE" in privileges
    if table_name in {"plan", "plan_matter"}:
        # Only Admin can delete plans
        assert "DELETE" not in privileges
    else:
        assert "DELETE" in privileges


@pytest.mark.parametrize("table_name", code_tables())
def test_read_write_role_privileges_on_code_tables(
    db_connection: Connection, table_name: str
) -> None:
    privileges = table_privileges(db_connection, "codes", table_name, ROLE_READ_WRITE)
    assert "SELECT" in privileges
    assert "INSERT" not in privileges
    assert "UPDATE" not in privileges
    assert "DELETE" not in privileges


def foreign_keys() -> list[tuple[str, str, str]]:
    return [
        (table.schema, table.name, column.name)
        for table in Base.metadata.tables.values()
        for column in table.columns
        if table.schema in {"hame", "codes"} and column.foreign_keys
    ]


@pytest.mark.skip
@pytest.mark.parametrize(("table_schema", "table_name", "column_name"), foreign_keys())
def test_each_foreign_key_has_an_index(
    db_connection: Connection, table_schema: str, table_name: str, column_name: str
) -> None:
    with db_connection.cursor() as cur:
        cur.execute(
            "SELECT indexname "
            "FROM pg_indexes "
            "WHERE schemaname = %s "
            "  AND tablename = %s "
            "  AND indexdef LIKE %s;",
            (table_schema, table_name, f"%({column_name})%"),
        )
        indexes = cur.fetchall()
        assert indexes, (
            f"No index found for foreign key {table_schema}.{table_name}.{column_name}"
        )


def geom_columns() -> list[tuple[str, str, str]]:
    return [
        (table.schema, table.name, column.name)
        for table in Base.metadata.tables.values()
        for column in table.columns
        if table.schema in {"hame", "codes"} and column.name == "geom"
    ]


@pytest.mark.parametrize(("table_schema", "table_name", "column_name"), geom_columns())
def test_all_geometry_columns_have_a_spatial_index(
    db_connection: Connection, table_schema: str, table_name: str, column_name: str
) -> None:
    with db_connection.cursor() as cur:
        cur.execute(
            "SELECT indexname "
            "FROM pg_indexes "
            "WHERE schemaname = %s "
            "  AND tablename = %s "
            "  AND indexdef LIKE %s;",
            (table_schema, table_name, f"%USING gist ({column_name})%"),
        )
        indexes = cur.fetchall()
        assert indexes, (
            f"No spatial index found for geometry column {table_schema}.{table_name}.{column_name}"
        )


# A role shaped like the AWS RDS master user, which is NOSUPERUSER. The local SU
# user is a real superuser, so it would not hit the PostgreSQL 16 rules at all.
FAKE_RDS_MASTER = "test_rds_master"
FAKE_RDS_DBA = "test_rds_dba"
FAKE_RDS_DB = "test_rds_db"
FAKE_RDS_PASSWORD = "test_rds"  # noqa: S105


def drop_fake_rds_objects(conn: Connection) -> None:
    conn.execute(
        SQL("DROP DATABASE IF EXISTS {db_name}").format(db_name=Identifier(FAKE_RDS_DB))
    )
    for role in (FAKE_RDS_DBA, FAKE_RDS_MASTER):
        if (
            conn.execute(
                "SELECT 1 FROM pg_roles WHERE rolname = %s", (role,)
            ).fetchone()
            is None
        ):
            continue
        # Privileges granted to a role must go before the role itself.
        conn.execute(SQL("DROP OWNED BY {role}").format(role=Identifier(role)))
        conn.execute(SQL("DROP ROLE {role}").format(role=Identifier(role)))


@pytest.fixture
def fake_rds_master_params(
    root_db_params: ConnectionParameters, monkeypatch: pytest.MonkeyPatch
) -> Generator[ConnectionParameters]:
    """Connection parameters for a non-superuser role that mimics the RDS master.

    Also points db_manager at a throwaway DBA user, so the fixture never touches
    the real arho_dba role or the main database.
    """
    with psycopg.connect(**root_db_params, autocommit=True) as su_conn:
        drop_fake_rds_objects(su_conn)
        su_conn.execute(
            SQL(
                "CREATE ROLE {master} WITH LOGIN CREATEDB CREATEROLE NOSUPERUSER "
                "ENCRYPTED PASSWORD {password}"
            ).format(
                master=Identifier(FAKE_RDS_MASTER), password=Literal(FAKE_RDS_PASSWORD)
            )
        )
        # On RDS the master user owns the maintenance database. Here it does not,
        # and configure_db_permissions has revoked CONNECT from PUBLIC.
        su_conn.execute(
            SQL("GRANT CONNECT ON DATABASE {db_name} TO {master}").format(
                db_name=Identifier(root_db_params["dbname"]),
                master=Identifier(FAKE_RDS_MASTER),
            )
        )

    monkeypatch.setattr(
        db_manager,
        "dba_user_credentials",
        UserCredentials(username=FAKE_RDS_DBA, password=FAKE_RDS_PASSWORD),
    )

    yield {**root_db_params, "user": FAKE_RDS_MASTER, "password": FAKE_RDS_PASSWORD}

    with psycopg.connect(**root_db_params, autocommit=True) as su_conn:
        drop_fake_rds_objects(su_conn)


def test_creating_a_database_needs_the_set_option_on_its_owner(
    fake_rds_master_params: ConnectionParameters,
) -> None:
    """Show why the grant is needed.

    Since PostgreSQL 16 a CREATEROLE user only gets ADMIN OPTION on a role it
    creates, and CREATE DATABASE ... OWNER needs the SET option as well.
    """
    with psycopg.connect(**fake_rds_master_params) as conn:
        db_manager.create_dba_user_if_not_exists(conn)
        with pytest.raises(psycopg.errors.InsufficientPrivilege):
            db_manager.create_db_if_not_exists(conn, FAKE_RDS_DB)


def test_non_superuser_can_create_a_database_owned_by_the_dba_user(
    fake_rds_master_params: ConnectionParameters,
) -> None:
    with psycopg.connect(**fake_rds_master_params) as conn:
        db_manager.create_dba_user_if_not_exists(conn)
        db_manager.grant_dba_role_to_su_user(conn)
        db_manager.create_db_if_not_exists(conn, FAKE_RDS_DB)

        owner = conn.execute(
            "SELECT pg_get_userbyid(datdba) FROM pg_database WHERE datname = %s",
            (FAKE_RDS_DB,),
        ).fetchone()

    assert owner == (FAKE_RDS_DBA,)
