from __future__ import annotations

import inspect
import json
import uuid
from http import HTTPStatus
from typing import TYPE_CHECKING, Any
from urllib.parse import urlsplit, urlunsplit

import psycopg
import pytest
import requests

from database import codes

from .conftest import deepcompare

if TYPE_CHECKING:
    from collections.abc import Callable

    from pytest_docker.plugin import Services

    from database.db_helper import ConnectionParameters
    from database.models import Plan, PlanMatter
    from lambdas.koodistot_loader import koodistot_loader


@pytest.fixture(scope="module")
def db_manager_url(docker_ip: str | Any, docker_services: Services) -> str:
    port = docker_services.port_for("db_manager", 8080)
    return f"http://{docker_ip}:{port}/2015-03-31/functions/function/invocations"


@pytest.fixture(scope="module")
def koodistot_loader_url(docker_ip: str | Any, docker_services: Services) -> str:
    port = docker_services.port_for("koodistot_loader", 8080)
    return f"http://{docker_ip}:{port}/2015-03-31/functions/function/invocations"


@pytest.fixture(scope="module")
def ryhti_client_url(docker_ip: str | Any, docker_services: Services) -> str:
    port = docker_services.port_for("ryhti_client", 8080)
    return f"http://{docker_ip}:{port}/2015-03-31/functions/function/invocations"


@pytest.fixture(scope="module")
def mml_loader_url(docker_ip: str | Any, docker_services: Services) -> str:
    port = docker_services.port_for("mml_loader", 8080)
    return f"http://{docker_ip}:{port}/2015-03-31/functions/function/invocations"


@pytest.fixture(scope="module")
def fetch_presigned(
    docker_ip: str | Any, docker_services: Services
) -> Callable[..., requests.Response]:
    """Fetch a presigned URL generated by the lambda container.

    The URL points at the compose-internal minio host, which is not resolvable
    from the test host. Connect via docker_ip instead, but keep the original
    Host header so the presigned signature stays valid.
    """
    minio_port = docker_services.port_for("minio", 9000)

    def _fetch(
        url: str, method: str = "get", data: bytes | None = None
    ) -> requests.Response:
        parts = urlsplit(url)
        reachable = urlunsplit(parts._replace(netloc=f"{docker_ip}:{minio_port}"))
        return requests.request(
            method, reachable, headers={"Host": parts.netloc}, data=data
        )

    return _fetch


@pytest.fixture
def upload_plan_file(
    ryhti_client_url: str, fetch_presigned: Callable[..., requests.Response]
) -> Callable[[str], str]:
    """Request a presigned upload URL from the lambda and upload a plan file.

    Returns the S3 key of the uploaded file, to be passed to import_plan.
    """

    def _upload(plan_json: str) -> str:
        r = requests.post(
            ryhti_client_url, data=json.dumps({"action": "get_upload_url"})
        )
        assert r.status_code == HTTPStatus.OK
        data = r.json()
        assert data["statusCode"] == HTTPStatus.OK
        details = data["body"]["details"]
        assert details["key"].startswith("import/")
        put_response = fetch_presigned(
            details["upload_url"], method="put", data=plan_json.encode("utf-8")
        )
        assert put_response.status_code == HTTPStatus.OK
        return details["key"]

    return _upload


@pytest.fixture
def populate_koodistot(koodistot_loader_url: str) -> None:
    payload: koodistot_loader.Event = {}
    r = requests.post(koodistot_loader_url, data=json.dumps(payload))
    data = r.json()
    assert data["statusCode"] == 200, data["body"]


@pytest.fixture
def populate_suomifi_koodistot(koodistot_loader_url: str) -> None:
    payload: koodistot_loader.Event = {"local_codes": False}
    r = requests.post(koodistot_loader_url, data=json.dumps(payload))
    data = r.json()
    assert data["statusCode"] == 200, data["body"]


@pytest.fixture
def populate_local_koodistot(koodistot_loader_url: str) -> None:
    payload: koodistot_loader.Event = {"suomifi_codes": False}
    r = requests.post(koodistot_loader_url, data=json.dumps(payload))
    data = r.json()
    assert data["statusCode"] == 200, data["body"]


def test_populate_koodistot(
    populate_koodistot: None, main_db_params: ConnectionParameters
) -> None:
    """Test the whole lambda endpoint"""
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            for _name, value in inspect.getmembers(codes, inspect.isclass):
                if issubclass(value, codes.CodeBase) and (
                    # some code tables have external source, some have local source, some have both
                    value.code_list_uri or value.local_codes
                ):
                    print(value)
                    cur.execute(f"SELECT count(*) FROM codes.{value.__tablename__}")
                    row = cur.fetchone()
                    assert row is not None
                    code_count = row[0]
                    assert code_count > 0
    finally:
        conn.close()


def test_populate_suomifi_koodistot(
    populate_suomifi_koodistot: None, main_db_params: ConnectionParameters
) -> None:
    """Test only suomi.fi codes"""
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            for _name, value in inspect.getmembers(codes, inspect.isclass):
                if (
                    value is not codes.CodeBase
                    and issubclass(value, codes.CodeBase)
                    and (
                        # some code tables have external source, some have local source, some have both
                        value.code_list_uri
                    )
                ):
                    cur.execute(f"SELECT count(*) FROM codes.{value.__tablename__}")
                    row = cur.fetchone()
                    assert row is not None
                    code_count = row[0]
                    assert code_count > 0
                if (
                    value is not codes.CodeBase
                    and issubclass(value, codes.CodeBase)
                    and (
                        # some code tables have external source, some have local source, some have both
                        not value.code_list_uri
                    )
                ):
                    cur.execute(f"SELECT count(*) FROM codes.{value.__tablename__}")
                    row = cur.fetchone()
                    assert row is not None
                    code_count = row[0]
                    assert code_count == 0
    finally:
        conn.close()


def test_populate_local_koodistot(
    populate_local_koodistot: None, main_db_params: ConnectionParameters
) -> None:
    """Test only local codes"""
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            for _name, value in inspect.getmembers(codes, inspect.isclass):
                if (
                    value is not codes.CodeBase
                    and issubclass(value, codes.CodeBase)
                    and (
                        # some code tables have external source, some have local source, some have both
                        not value.local_codes
                    )
                ):
                    cur.execute(f"SELECT count(*) FROM codes.{value.__tablename__}")
                    row = cur.fetchone()
                    assert row is not None
                    code_count = row[0]
                    assert code_count == 0
                if (
                    value is not codes.CodeBase
                    and issubclass(value, codes.CodeBase)
                    and (
                        # some code tables have external source, some have local source, some have both
                        value.local_codes
                    )
                ):
                    cur.execute(f"SELECT count(*) FROM codes.{value.__tablename__}")
                    row = cur.fetchone()
                    assert row is not None
                    code_count = row[0]
                    assert code_count > 0
    finally:
        conn.close()


# Test getting a plan with both direct lambda call and HTTPS API call.
# The HTTPS API call body will be a JSON string.
@pytest.fixture(params=["direct", "api_gateway"])
def get_plan(
    request: pytest.FixtureRequest,
    ryhti_client_url: str,
    fetch_presigned: Callable[..., requests.Response],
    complete_test_plan: Plan,
    another_test_plan: Plan,
    desired_plan_dict: dict,
) -> None:
    """Get invalid plan JSON from lambda. The plan should be validated separately.

    Getting a plan should make lambda return http 200 OK (to indicate that
    serialization has been run successfully), with ryhti_response empty, and
    details containing the download URL for the serialized plan. The downloaded
    file contains a single bare plan JSON; another plan in the database must not
    be serialized.

    If the request is coming through the API Gateway with stringified JSON body, the
    response to the API gateway must similarly contain stringified JSON body.
    """
    event = {
        "action": "get_plan",
        "plan_uuid": complete_test_plan.id,
        "save_json": True,
    }
    payload: dict[str, Any] = event
    if request.param == "api_gateway":
        payload = {
            "version": "2.0",
            "routeKey": "",
            "rawPath": "",
            "rawQueryString": "",
            "cookies": [],
            "headers": {},
            "queryStringParameters": {},
            "requestContext": {},
            "body": json.dumps(event),
            "pathParameters": {},
            "isBase64Encoded": False,
            "stageVariables": {},
        }
    r = requests.post(ryhti_client_url, data=json.dumps(payload))
    data = r.json()
    print(data)
    assert data["statusCode"] == 200
    body = data["body"]
    if request.param == "api_gateway":
        # API gateway response must have JSON body stringified.
        body = json.loads(body)
    assert body["title"] == "Returning serialized plan from database."
    assert body["details"]["key"].startswith("export/")
    download_response = fetch_presigned(body["details"]["download_url"])
    assert download_response.status_code == HTTPStatus.OK
    plan_dictionary = download_response.json()
    deepcompare(
        plan_dictionary,
        desired_plan_dict,
        ignore_order_for_keys=[
            "planRegulationGroups",
            "planRegulationGroupRelations",
            "additionalInformations",
        ],
    )
    assert body["ryhti_response"] is None


def test_get_plan(get_plan: None, main_db_params: ConnectionParameters) -> None:
    """Test the whole lambda endpoint with an invalid plan"""
    # getting plan JSON from lambda should not run validations
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            # Check that plans are NOT validated
            cur.execute("SELECT validated_at, validation_errors FROM hame.plan")
            row = cur.fetchone()
            assert row is not None
            validation_date, errors = row
            assert not validation_date
            assert not errors

            row = cur.fetchone()
            assert row is not None
            validation_date, errors = row
            assert not validation_date
            assert not errors
    finally:
        conn.close()


@pytest.fixture
def validate_single_valid_plan(
    ryhti_client_url: str, complete_test_plan: Plan, another_test_plan
) -> None:
    """Validate a valid Ryhti plan against the Ryhti API.

    A valid plan should make lambda return http 200 OK, with no validation
    errors in the payload.
    """
    payload = {
        "action": "validate_plan",
        "plan_uuid": complete_test_plan.id,
        "save_json": True,
    }
    r = requests.post(ryhti_client_url, data=json.dumps(payload))
    data = r.json()
    print(data)
    assert data["statusCode"] == 200
    body = data["body"]
    assert body["title"] == "Plan validation run."
    assert body["details"] == f"Plan validation successful for {complete_test_plan.id}!"
    # Our test plan is valid
    assert body["ryhti_response"]["status"] == 200
    assert not body["ryhti_response"]["errors"]


def test_validate_single_valid_plan(
    validate_single_valid_plan: None, main_db_params: ConnectionParameters
) -> None:
    """Test the whole lambda endpoint with a valid plan"""
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT validated_at, validation_errors FROM hame.plan ORDER BY modified_at DESC"
            )
            row = cur.fetchone()
            assert row is not None
            validation_date, errors = row
            assert validation_date
            assert errors == "Kaava on validi. Kaava-asiaa ei ole vielä validoitu."

            # Check that other plan is NOT marked validated
            row = cur.fetchone()
            assert row is not None
            validation_date, errors = row
            assert not validation_date
            assert not errors
    finally:
        conn.close()


@pytest.fixture
def validate_single_invalid_plan(
    ryhti_client_url: str, complete_test_plan: Plan, another_test_plan
) -> None:
    """Validate an invalid Ryhti plan against the Ryhti API.

    An invalid plan should make lambda return http 200 OK (to indicate that the validation
    has been run successfully), with the validation errors returned in the payload.
    """
    payload = {
        "action": "validate_plan",
        "plan_uuid": another_test_plan.id,
        "save_json": True,
    }
    r = requests.post(ryhti_client_url, data=json.dumps(payload))
    data = r.json()
    print(data)
    assert data["statusCode"] == 200
    body = data["body"]
    assert body["title"] == "Plan validation run."
    assert body["details"] == f"Plan validation FAILED for {another_test_plan.id}."
    assert body["ryhti_response"]["status"] == 400
    assert body["ryhti_response"]["errors"]


def test_validate_single_invalid_plan(
    validate_single_invalid_plan: None, main_db_params: ConnectionParameters
) -> None:
    """Test the whole lambda endpoint with an invalid plan"""
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT validated_at, validation_errors FROM hame.plan ORDER BY modified_at DESC"
            )
            row = cur.fetchone()
            assert row is not None
            validation_date, errors = row
            assert validation_date
            assert errors

            # Check that other plan is NOT marked validated
            row = cur.fetchone()
            assert row is not None
            validation_date, errors = row
            assert not validation_date
            assert not errors
    finally:
        conn.close()


@pytest.fixture
def get_permanent_plan_identifier(
    ryhti_client_url: str,
    complete_test_plan: Plan,
    another_test_plan: Plan,
    desired_plan_dict: dict,
) -> None:
    """Get a permanent plan identifier from X-road. Another plan in the database should not
    get a permanent plan identifier.

    Since local tests or CI/CD cannot connect to X-Road servers, we use a Mock X-Road API
    that returns a permanent plan identifier and responds with 200 OK.

    Getting an identifier should make lambda return http 200 OK, with the
    ryhti_response and details both containing the identifier.
    """
    payload = {
        "action": "get_permanent_plan_identifier",
        "plan_uuid": complete_test_plan.id,
        "save_json": True,
    }
    r = requests.post(ryhti_client_url, data=json.dumps(payload))
    data = r.json()
    print(data)
    assert data["statusCode"] == 200
    body = data["body"]
    assert body["title"] == "Possible permanent plan identifier set."
    assert body["details"] == "MK-123456"
    assert body["ryhti_response"]["status"] == 200
    assert body["ryhti_response"]["detail"] == "MK-123456"


def test_get_permanent_plan_identifier(
    get_permanent_plan_identifier: None, main_db_params: ConnectionParameters
) -> None:
    """Test the whole lambda endpoint with single_plan"""
    # getting permanent identifier from lambda should not run validations
    conn = psycopg.connect(**main_db_params)
    try:
        with conn.cursor() as cur:
            # Check that plans are NOT validated
            cur.execute(
                """
                SELECT validated_at, validation_errors, pm.permanent_plan_identifier
                FROM hame.plan p JOIN hame.plan_matter pm
                ON p.plan_matter_id = pm.id
                ORDER BY p.modified_at DESC
                """
            )
            row = cur.fetchone()
            assert row is not None
            validation_date, errors, permanent_plan_identifier = row
            assert not validation_date
            assert not errors
            assert not permanent_plan_identifier

            row = cur.fetchone()
            assert row is not None
            validation_date, errors, permanent_plan_identifier = row
            assert not validation_date
            assert not errors
            assert permanent_plan_identifier == "MK-123456"
    finally:
        conn.close()


@pytest.fixture
def extra_data(plan_matter_instance: PlanMatter) -> dict:
    return {"name": "test_plan", "plan_matter_id": plan_matter_instance.id}


@pytest.fixture
def import_payload(extra_data):
    return {"action": "import_plan", "data": {"s3_key": None, "extra_data": extra_data}}


def test_import_plan(
    codes_loaded,
    import_payload,
    ryhti_client_url,
    upload_plan_file: Callable[[str], str],
    simple_plan_json: str,
):
    """Test importing a plan"""
    import_payload["data"]["s3_key"] = upload_plan_file(simple_plan_json)

    r = requests.post(ryhti_client_url, data=json.dumps(import_payload))
    assert r.status_code == HTTPStatus.OK

    data = r.json()
    assert data["body"]["title"] == "Plan imported."
    assert data["body"]["details"]["plan_id"] == "7f522b2f-8b45-4a17-b433-5f47271b579e"


def test_import_duplicate_plan(
    codes_loaded,
    import_payload: dict[str, Any],
    ryhti_client_url: str,
    upload_plan_file: Callable[[str], str],
    simple_plan_json: str,
):
    """Test importing a plan"""
    import_payload["data"]["s3_key"] = upload_plan_file(simple_plan_json)

    r = requests.post(ryhti_client_url, data=json.dumps(import_payload))
    assert r.status_code == HTTPStatus.OK

    r = requests.post(ryhti_client_url, data=json.dumps(import_payload))
    assert (
        r.status_code == HTTPStatus.OK
    )  # TODO: This should be a 400 or 409. Fix after plugin fixed.

    data = r.json()
    assert data["body"]["title"] == "Plan already exists."


def test_import_invalid_plan(
    ryhti_client_url,
    import_payload,
    upload_plan_file: Callable[[str], str],
    invalid_plan_json: str,
):
    import_payload["data"]["s3_key"] = upload_plan_file(invalid_plan_json)

    r = requests.post(ryhti_client_url, data=json.dumps(import_payload))

    # Status code from the lambda container
    # (API Gateway would follow the status code returned from the lambda function)
    assert r.status_code == HTTPStatus.OK

    data = r.json()
    assert (
        data["statusCode"] == HTTPStatus.BAD_REQUEST
    )  # Status code from our lambda function
    assert data["body"]["title"] == "Error in provided data."
    assert "Invalid plan data:" in data["body"]["details"]["error"]


def test_import_missing_upload(codes_loaded, import_payload, ryhti_client_url):
    """Importing with an s3_key that was never uploaded should return 400."""
    import_payload["data"]["s3_key"] = (
        "import/00000000-0000-0000-0000-000000000000.json"
    )

    r = requests.post(ryhti_client_url, data=json.dumps(import_payload))
    assert r.status_code == HTTPStatus.OK

    data = r.json()
    assert data["statusCode"] == HTTPStatus.BAD_REQUEST
    assert data["body"]["title"] == "Uploaded plan file not found."


def test_missing_action(ryhti_client_url: str) -> None:
    """An event without an action should return 400."""
    r = requests.post(ryhti_client_url, data=json.dumps({}))
    assert r.status_code == HTTPStatus.OK

    data = r.json()
    assert data["statusCode"] == HTTPStatus.BAD_REQUEST
    assert data["body"]["title"] == "Missing action."


def test_validate_plan_without_plan_uuid(ryhti_client_url: str) -> None:
    """Validating without a plan_uuid should return 400."""
    r = requests.post(ryhti_client_url, data=json.dumps({"action": "validate_plan"}))
    assert r.status_code == HTTPStatus.OK

    data = r.json()
    assert data["statusCode"] == HTTPStatus.BAD_REQUEST
    assert data["body"]["title"] == "Missing plan_uuid."


def test_get_unknown_plan(ryhti_client_url: str, complete_test_plan: Plan) -> None:
    """Getting a plan that does not exist should return 404."""
    payload = {"action": "get_plan", "plan_uuid": str(uuid.uuid4())}
    r = requests.post(ryhti_client_url, data=json.dumps(payload))
    assert r.status_code == HTTPStatus.OK

    data = r.json()
    assert data["statusCode"] == HTTPStatus.NOT_FOUND
    assert data["body"]["title"] == "Plan not found."
