exclude: ".enc.json$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: docker-compose.clear-mounts.yml # yaml check don't like !reset tag
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        exclude: ^migrations/
        additional_dependencies:
          - alembic
          - alembic_utils
          - geoalchemy2
          - psycopg[binary]
          - pydantic
          - pytest
          - requests-mock
          - sqlalchemy
          - types-boto3
          - types-requests
          - types-shapely
          - types-simplejson

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear~=24.1.17
          - pep8-naming~=0.13.3
