include:
  - arho.*
  - codes.*

viewpoints:
  -
    name: All tables
    desc: All tables that make up maakuntakaava plan data.
    tables:
      - arho.plan
      - arho.land_use_area
      - arho.other_area
      - arho.line
      - arho.land_use_point
      - arho.other_point
      - arho.plan_regulation_group
      - arho.plan_regulation
      - arho.plan_proposition
      - arho.document
      - arho.source_data
      - arho.organisation
      - arho.lifecycle_date
      - codes.administrative_region
      - codes.lifecycle_status
      - codes.plan_theme
      - codes.plan_type
      - codes.type_of_additional_information
      - codes.type_of_document
      - codes.type_of_plan_regulation_group
      - codes.type_of_plan_regulation
      - codes.type_of_source_data
      - codes.type_of_underground
      - codes.type_of_verbal_plan_regulation
      - codes.category_of_publicity
      - codes.name_of_plan_case_decision
      - codes.type_of_decision_maker
      - codes.type_of_interaction_event
      - codes.type_of_processing_event

    groups:
      -
        name: Plan geometry tables
        desc: These tables represent all geometries in the plan.
        tables:
          - arho.plan
          - arho.land_use_area
          - arho.other_area
          - arho.line
          - arho.land_use_point
          - arho.other_point
      -
        name: Plan regulation tables
        desc: These tables represent all regulations in the plan.
        tables:
          - arho.plan_regulation_group
          - arho.plan_regulation
          - arho.plan_proposition
      -
        name: Plan metadata tables
        desc: These tables contain all metadata, documents and other linked information.
        tables:
          - arho.document
          - arho.source_data
          - arho.organisation
          - arho.lifecycle_date
      -
        name: Code tables
        desc: These tables contain all national (koodistot.suomi.fi) and local codes used for classifying plan data.
        tables:
          - codes.administrative_region
          - codes.lifecycle_status
          - codes.plan_theme
          - codes.plan_type
          - codes.type_of_additional_information
          - codes.type_of_document
          - codes.type_of_plan_regulation_group
          - codes.type_of_plan_regulation
          - codes.type_of_source_data
          - codes.type_of_underground
          - codes.type_of_verbal_plan_regulation
          - codes.category_of_publicity
          - codes.name_of_plan_case_decision
          - codes.type_of_decision_maker
          - codes.type_of_interaction_event
          - codes.type_of_processing_event
