version: "3.9"
services:
  db:
    image: postgis/postgis:13-master
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: ["postgres", "-c", "log_statement=all"]

  db_manager:
    build:
      context: .
      dockerfile: database/db_manager.Dockerfile
    env_file:
      - .env.dev
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./database/db_manager/db_manager.py:/var/task/app.py

  koodistot_loader:
    build:
      context: .
      dockerfile: database/koodistot_loader.Dockerfile
    env_file:
      - .env.dev
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
    ports:
      - "8082:8080"
    depends_on:
      - db
    volumes:
      - ./database/koodistot_loader/koodistot_loader.py:/var/task/app.py
