volumes:
  postgis-data:

services:
  db:
    image: postgis/postgis:13-master
    ports:
      - ${DB_INSTANCE_PORT:-5434}:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgis-data:/var/lib/postgresql/data
      - ./pg_dumps:/opt/pg_backups

    command: ["postgres", "-c", "log_statement=all"]

  db_manager:
    build:
      context: .
      dockerfile: lambdas/db_manager/db_manager.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
    ports:
      - ${DB_MANAGER_PORT:-8081}:8080
    depends_on:
      - db
    volumes:
      - ./lambdas/db_manager/db_manager.py:/var/task/db_manager.py
      - ./database:/var/task/database
      - ./migrations:/var/task/migrations

  koodistot_loader:
    build:
      context: .
      dockerfile: lambdas/koodistot_loader/koodistot_loader.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
    ports:
      - ${KOODISTOT_LOADER_PORT:-8082}:8080
    depends_on:
      - db
    volumes:
      - ./lambdas/koodistot_loader/koodistot_loader.py:/var/task/koodistot_loader.py
      - ./database:/var/task/database

  ryhti_client:
    build:
      context: .
      dockerfile: lambdas/ryhti_client/ryhti_client.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
      - SYKE_APIKEY
      - XROAD_HTTP_PORT=1080
      - XROAD_SERVER_ADDRESS=mock_xroad
      - XROAD_MEMBER_CLASS=COM
      - XROAD_MEMBER_CODE=2455538-5
      - XROAD_MEMBER_CLIENT_NAME=ryhti-gispo-client
      - XROAD_SYKE_CLIENT_ID=test-id
      - XROAD_SYKE_CLIENT_SECRET=test-secret
    ports:
      - ${RYHTI_CLIENT_PORT:-8083}:8080
    depends_on:
      - db
      - mock_xroad
    volumes:
      - ./ryhti_debug:/var/task/ryhti_debug
      - ./lambdas/ryhti_client/ryhti_client.py:/var/task/ryhti_client.py
      - ./database:/var/task/database

  mml_loader:
    build:
      context: .
      dockerfile: lambdas/mml_loader/mml_loader.Dockerfile
    env_file:
      - .env
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
      - READ_FROM_AWS=0
      - MML_APIKEY
    ports:
      - ${MML_LOADER_PORT:-8085}:8080
    depends_on:
      - db
    volumes:
      - ./lambdas/mml_loader/mml_loader.py:/var/task/mml_loader.py
      - ./database:/var/task/database

  mock_xroad:
    image: mockserver/mockserver:latest
    ports:
      - ${MOCK_SERVER_PORT:-8443}:1080
    environment:
      - MOCKSERVER_WATCH_INITIALIZATION_JSON="true"
      - MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
    volumes:
      - ./test/test_services_mock_xroad.json:/config/initializerJson.json:Z
