version: "3.9"
services:
  db:
    image: postgis/postgis:13-master
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  db_manager:
    build:
      context: database/db_manager
    env_file:
      - .env.dev
    environment:
      - DB_INSTANCE_ADDRESS=db
      - DB_INSTANCE_PORT=5432
    ports:
      - "8081:8080"
    depends_on:
      - db
    volumes:
      - ./database/db_manager/db_manager.py:/var/task/app.py
