"""Update views

Revision ID: 7f5ef657d2d6
Revises: f062ce5225e1
Create Date: 2025-11-17 21:45:09.198464

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_view import PGView
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "7f5ef657d2d6"
down_revision: str | None = "f062ce5225e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_land_use_area_v = PGView(
        schema="hame",
        signature="land_use_area_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    modified_at,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('land_use_area', id) short_names,\n    hame.primary_use_regulations(id) primary_use,\n    hame.regulation_values('land_use_area', id) regulation_values\nfrom\n    hame.land_use_area",
    )
    op.replace_entity(hame_land_use_area_v)

    hame_other_area_v = PGView(
        schema="hame",
        signature="other_area_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    modified_at,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('other_area', id) short_names,\n    hame.sub_area_regulations(id) sub_area,\n    hame.regulation_values('other_area', id) regulation_values\nfrom\n    hame.other_area",
    )
    op.replace_entity(hame_other_area_v)

    hame_line_v = PGView(
        schema="hame",
        signature="line_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    modified_at,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('line', id) short_names,\n    hame.type_regulations('line', id) type_regulations,\n    hame.regulation_values('line', id) regulation_values\nfrom\n    hame.line",
    )
    op.replace_entity(hame_line_v)

    hame_point_v = PGView(
        schema="hame",
        signature="point_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    modified_at,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('point', id) short_names,\n    hame.type_regulations('point', id) type_regulations,\n    hame.regulation_values('point', id) regulation_values\nfrom\n    hame.point",
    )
    op.replace_entity(hame_point_v)

    # op.replace_entity drops and creates the view, so triggers must be recreated
    hame_land_use_area_v_trg_iiud_land_use_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_land_use_area_v",
        on_entity="hame.land_use_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.land_use_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_land_use_area_v_trg_iiud_land_use_area_v)

    hame_other_area_v_trg_iiud_other_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_other_area_v",
        on_entity="hame.other_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.other_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_other_area_v_trg_iiud_other_area_v)

    hame_point_v_trg_iiud_point_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_point_v",
        on_entity="hame.point_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.point_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_point_v_trg_iiud_point_v)

    hame_line_v_trg_iiud_line_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_line_v",
        on_entity="hame.line_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.line_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_line_v_trg_iiud_line_v)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_point_v = PGView(
        schema="hame",
        signature="point_v",
        definition="SELECT point.geom,\n    point.name,\n    point.description,\n    point.source_data_object,\n    point.height_min,\n    point.height_max,\n    point.height_unit,\n    point.height_reference_point,\n    point.ordering,\n    point.type_of_underground_id,\n    point.plan_id,\n    point.exported_at,\n    point.lifecycle_status_id,\n    point.id,\n    point.created_at,\n    point.modified_at,\n    hame.short_names('point'::text, point.id) AS short_names,\n    hame.type_regulations('point'::text, point.id) AS type_regulations,\n    hame.regulation_values('point'::text, point.id) AS regulation_values\n   FROM hame.point",
    )
    op.replace_entity(hame_point_v)
    hame_line_v = PGView(
        schema="hame",
        signature="line_v",
        definition="SELECT line.geom,\n    line.name,\n    line.source_data_object,\n    line.height_unit,\n    line.ordering,\n    line.type_of_underground_id,\n    line.plan_id,\n    line.exported_at,\n    line.lifecycle_status_id,\n    line.id,\n    line.created_at,\n    line.modified_at,\n    line.description,\n    line.height_min,\n    line.height_max,\n    line.height_reference_point,\n    hame.short_names('line'::text, line.id) AS short_names,\n    hame.type_regulations('line'::text, line.id) AS type_regulations,\n    hame.regulation_values('line'::text, line.id) AS regulation_values\n   FROM hame.line",
    )
    op.replace_entity(hame_line_v)
    hame_other_area_v = PGView(
        schema="hame",
        signature="other_area_v",
        definition="SELECT other_area.geom,\n    other_area.name,\n    other_area.source_data_object,\n    other_area.height_unit,\n    other_area.ordering,\n    other_area.type_of_underground_id,\n    other_area.plan_id,\n    other_area.exported_at,\n    other_area.lifecycle_status_id,\n    other_area.id,\n    other_area.created_at,\n    other_area.modified_at,\n    other_area.description,\n    other_area.height_min,\n    other_area.height_max,\n    other_area.height_reference_point,\n    hame.short_names('other_area'::text, other_area.id) AS short_names,\n    hame.sub_area_regulations(other_area.id) AS sub_area,\n    hame.regulation_values('other_area'::text, other_area.id) AS regulation_values\n   FROM hame.other_area",
    )
    op.replace_entity(hame_other_area_v)
    hame_land_use_area_v = PGView(
        schema="hame",
        signature="land_use_area_v",
        definition="SELECT land_use_area.geom,\n    land_use_area.name,\n    land_use_area.source_data_object,\n    land_use_area.height_unit,\n    land_use_area.ordering,\n    land_use_area.type_of_underground_id,\n    land_use_area.plan_id,\n    land_use_area.exported_at,\n    land_use_area.lifecycle_status_id,\n    land_use_area.id,\n    land_use_area.created_at,\n    land_use_area.modified_at,\n    land_use_area.description,\n    land_use_area.height_min,\n    land_use_area.height_max,\n    land_use_area.height_reference_point,\n    hame.short_names('land_use_area'::text, land_use_area.id) AS short_names,\n    hame.primary_use_regulations(land_use_area.id) AS primary_use,\n    hame.regulation_values('land_use_area'::text, land_use_area.id) AS regulation_values\n   FROM hame.land_use_area",
    )
    op.replace_entity(hame_land_use_area_v)
    
    # op.replace_entity drops and creates the view, so triggers must be recreated
    hame_land_use_area_v_trg_iiud_land_use_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_land_use_area_v",
        on_entity="hame.land_use_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.land_use_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_land_use_area_v_trg_iiud_land_use_area_v)

    hame_other_area_v_trg_iiud_other_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_other_area_v",
        on_entity="hame.other_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.other_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_other_area_v_trg_iiud_other_area_v)

    hame_point_v_trg_iiud_point_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_point_v",
        on_entity="hame.point_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.point_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_point_v_trg_iiud_point_v)

    hame_line_v_trg_iiud_line_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_line_v",
        on_entity="hame.line_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.line_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_line_v_trg_iiud_line_v)
