"""Add approval_date column

Revision ID: a9466024d166
Revises: 7cf6938975d6
Create Date: 2025-11-17 16:18:52.715170

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9466024d166"
down_revision: str | None = "7cf6938975d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan", sa.Column("approval_date", sa.Date(), nullable=True), schema="hame"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "approval_date", schema="hame")
    # ### end Alembic commands ###
