"""Add period_of_validity columns

Revision ID: f062ce5225e1
Revises: a9466024d166
Create Date: 2025-11-17 16:52:35.529436

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f062ce5225e1"
down_revision: str | None = "a9466024d166"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "land_use_area",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "land_use_area",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "line",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "line",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "other_area",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "other_area",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_proposition",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_proposition",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "point",
        sa.Column("period_of_validity_start", sa.Date(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "point",
        sa.Column("period_of_validity_end", sa.Date(), nullable=True),
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("point", "period_of_validity_end", schema="hame")
    op.drop_column("point", "period_of_validity_start", schema="hame")
    op.drop_column("plan_regulation", "period_of_validity_end", schema="hame")
    op.drop_column("plan_regulation", "period_of_validity_start", schema="hame")
    op.drop_column("plan_proposition", "period_of_validity_end", schema="hame")
    op.drop_column("plan_proposition", "period_of_validity_start", schema="hame")
    op.drop_column("plan", "period_of_validity_end", schema="hame")
    op.drop_column("plan", "period_of_validity_start", schema="hame")
    op.drop_column("other_area", "period_of_validity_end", schema="hame")
    op.drop_column("other_area", "period_of_validity_start", schema="hame")
    op.drop_column("line", "period_of_validity_end", schema="hame")
    op.drop_column("line", "period_of_validity_start", schema="hame")
    op.drop_column("land_use_area", "period_of_validity_end", schema="hame")
    op.drop_column("land_use_area", "period_of_validity_start", schema="hame")
    # ### end Alembic commands ###
