"""Add official_use_only column

Revision ID: 7cf6938975d6
Revises: 28c3a346e9c9
Create Date: 2025-11-17 16:13:00.322160

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cf6938975d6"
down_revision: str | None = "28c3a346e9c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan",
        sa.Column("official_use_only", sa.Boolean(), nullable=True),
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "official_use_only", schema="hame")
    # ### end Alembic commands ###
