"""add creator and modifier

Revision ID: 8f72c4abf6bd
Revises: 437ffa34d4d2
Create Date: 2026-01-30 11:22:18.928268

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f72c4abf6bd"
down_revision: str | None = "437ffa34d4d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "administrative_region",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "administrative_region",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "category_of_publicity",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "category_of_publicity",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "language", sa.Column("creator", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "language", sa.Column("modifier", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "legal_effects_of_master_plan",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "legal_effects_of_master_plan",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "lifecycle_status",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "lifecycle_status",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "municipality", sa.Column("creator", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "municipality",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "name_of_plan_case_decision",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "name_of_plan_case_decision",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "personal_data_content",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "personal_data_content",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "plan_theme", sa.Column("creator", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "plan_theme", sa.Column("modifier", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "plan_type", sa.Column("creator", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "plan_type", sa.Column("modifier", sa.String(), nullable=True), schema="codes"
    )
    op.add_column(
        "retention_time",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "retention_time",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_additional_information",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_additional_information",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_decision_maker",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_decision_maker",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_document",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_document",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_interaction_event",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_interaction_event",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_plan_regulation",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_plan_regulation",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_plan_regulation_group",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_plan_regulation_group",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_processing_event",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_processing_event",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_source_data",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_source_data",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_underground",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_underground",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_verbal_plan_regulation",
        sa.Column("creator", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "type_of_verbal_plan_regulation",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="codes",
    )
    op.add_column(
        "additional_information",
        sa.Column("creator", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "additional_information",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "document", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "document", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "event_date", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "event_date", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "land_use_area", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "land_use_area",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "lifecycle_date",
        sa.Column("creator", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "lifecycle_date",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "line", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "line", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "organisation", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "organisation", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "other_area", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "other_area", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "plan", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "plan", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "plan_matter", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "plan_matter", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "plan_proposition",
        sa.Column("creator", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_proposition",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation",
        sa.Column("creator", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation_group",
        sa.Column("creator", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "plan_regulation_group",
        sa.Column("modifier", sa.String(), nullable=True),
        schema="hame",
    )
    op.add_column(
        "point", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "point", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "source_data", sa.Column("creator", sa.String(), nullable=True), schema="hame"
    )
    op.add_column(
        "source_data", sa.Column("modifier", sa.String(), nullable=True), schema="hame"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_data", "modifier", schema="hame")
    op.drop_column("source_data", "creator", schema="hame")
    op.drop_column("point", "modifier", schema="hame")
    op.drop_column("point", "creator", schema="hame")
    op.drop_column("plan_regulation_group", "modifier", schema="hame")
    op.drop_column("plan_regulation_group", "creator", schema="hame")
    op.drop_column("plan_regulation", "modifier", schema="hame")
    op.drop_column("plan_regulation", "creator", schema="hame")
    op.drop_column("plan_proposition", "modifier", schema="hame")
    op.drop_column("plan_proposition", "creator", schema="hame")
    op.drop_column("plan_matter", "modifier", schema="hame")
    op.drop_column("plan_matter", "creator", schema="hame")
    op.drop_column("plan", "modifier", schema="hame")
    op.drop_column("plan", "creator", schema="hame")
    op.drop_column("other_area", "modifier", schema="hame")
    op.drop_column("other_area", "creator", schema="hame")
    op.drop_column("organisation", "modifier", schema="hame")
    op.drop_column("organisation", "creator", schema="hame")
    op.drop_column("line", "modifier", schema="hame")
    op.drop_column("line", "creator", schema="hame")
    op.drop_column("lifecycle_date", "modifier", schema="hame")
    op.drop_column("lifecycle_date", "creator", schema="hame")
    op.drop_column("land_use_area", "modifier", schema="hame")
    op.drop_column("land_use_area", "creator", schema="hame")
    op.drop_column("event_date", "modifier", schema="hame")
    op.drop_column("event_date", "creator", schema="hame")
    op.drop_column("document", "modifier", schema="hame")
    op.drop_column("document", "creator", schema="hame")
    op.drop_column("additional_information", "modifier", schema="hame")
    op.drop_column("additional_information", "creator", schema="hame")
    op.drop_column("type_of_verbal_plan_regulation", "modifier", schema="codes")
    op.drop_column("type_of_verbal_plan_regulation", "creator", schema="codes")
    op.drop_column("type_of_underground", "modifier", schema="codes")
    op.drop_column("type_of_underground", "creator", schema="codes")
    op.drop_column("type_of_source_data", "modifier", schema="codes")
    op.drop_column("type_of_source_data", "creator", schema="codes")
    op.drop_column("type_of_processing_event", "modifier", schema="codes")
    op.drop_column("type_of_processing_event", "creator", schema="codes")
    op.drop_column("type_of_plan_regulation_group", "modifier", schema="codes")
    op.drop_column("type_of_plan_regulation_group", "creator", schema="codes")
    op.drop_column("type_of_plan_regulation", "modifier", schema="codes")
    op.drop_column("type_of_plan_regulation", "creator", schema="codes")
    op.drop_column("type_of_interaction_event", "modifier", schema="codes")
    op.drop_column("type_of_interaction_event", "creator", schema="codes")
    op.drop_column("type_of_document", "modifier", schema="codes")
    op.drop_column("type_of_document", "creator", schema="codes")
    op.drop_column("type_of_decision_maker", "modifier", schema="codes")
    op.drop_column("type_of_decision_maker", "creator", schema="codes")
    op.drop_column("type_of_additional_information", "modifier", schema="codes")
    op.drop_column("type_of_additional_information", "creator", schema="codes")
    op.drop_column("retention_time", "modifier", schema="codes")
    op.drop_column("retention_time", "creator", schema="codes")
    op.drop_column("plan_type", "modifier", schema="codes")
    op.drop_column("plan_type", "creator", schema="codes")
    op.drop_column("plan_theme", "modifier", schema="codes")
    op.drop_column("plan_theme", "creator", schema="codes")
    op.drop_column("personal_data_content", "modifier", schema="codes")
    op.drop_column("personal_data_content", "creator", schema="codes")
    op.drop_column("name_of_plan_case_decision", "modifier", schema="codes")
    op.drop_column("name_of_plan_case_decision", "creator", schema="codes")
    op.drop_column("municipality", "modifier", schema="codes")
    op.drop_column("municipality", "creator", schema="codes")
    op.drop_column("lifecycle_status", "modifier", schema="codes")
    op.drop_column("lifecycle_status", "creator", schema="codes")
    op.drop_column("legal_effects_of_master_plan", "modifier", schema="codes")
    op.drop_column("legal_effects_of_master_plan", "creator", schema="codes")
    op.drop_column("language", "modifier", schema="codes")
    op.drop_column("language", "creator", schema="codes")
    op.drop_column("category_of_publicity", "modifier", schema="codes")
    op.drop_column("category_of_publicity", "creator", schema="codes")
    op.drop_column("administrative_region", "modifier", schema="codes")
    op.drop_column("administrative_region", "creator", schema="codes")
    # ### end Alembic commands ###
