"""remove geometry validation

Revision ID: 489b23cdab0a
Revises: 5c2431facab3
Create Date: 2026-02-02 15:25:30.269090

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "489b23cdab0a"
down_revision: str | None = "5c2431facab3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_trg_plan_validate_polygon_geometry = PGTrigger(
        schema="hame",
        signature="trg_plan_validate_polygon_geometry",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.plan FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_validate_polygon_geometry()",
    )
    op.drop_entity(hame_plan_trg_plan_validate_polygon_geometry)

    hame_line_trg_line_validate_geometry = PGTrigger(
        schema="hame",
        signature="trg_line_validate_geometry",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.line FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_line_validate_geometry()",
    )
    op.drop_entity(hame_line_trg_line_validate_geometry)

    hame_land_use_area_trg_land_use_area_validate_polygon_geometry = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_validate_polygon_geometry",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.land_use_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_validate_polygon_geometry()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_validate_polygon_geometry)

    hame_other_area_trg_other_area_validate_polygon_geometry = PGTrigger(
        schema="hame",
        signature="trg_other_area_validate_polygon_geometry",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.other_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_validate_polygon_geometry()",
    )
    op.drop_entity(hame_other_area_trg_other_area_validate_polygon_geometry)

    hame_trgfunc_validate_polygon_geometry = PGFunction(
        schema="hame",
        signature="trgfunc_validate_polygon_geometry()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF NOT ST_IsValid(NEW.geom) THEN\n            RAISE EXCEPTION 'Invalid geometry. Must follow OGC rules.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_validate_polygon_geometry)

    hame_trgfunc_line_validate_geometry = PGFunction(
        schema="hame",
        signature="trgfunc_line_validate_geometry()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF NOT ST_IsSimple(NEW.geom) THEN\n            RAISE EXCEPTION 'Invalid geometry. Must not intersect itself.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_line_validate_geometry)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_line_validate_geometry = PGFunction(
        schema="hame",
        signature="trgfunc_line_validate_geometry()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF NOT ST_IsSimple(NEW.geom) THEN\n            RAISE EXCEPTION 'Invalid geometry. Must not intersect itself.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_line_validate_geometry)

    hame_trgfunc_validate_polygon_geometry = PGFunction(
        schema="hame",
        signature="trgfunc_validate_polygon_geometry()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF NOT ST_IsValid(NEW.geom) THEN\n            RAISE EXCEPTION 'Invalid geometry. Must follow OGC rules.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_validate_polygon_geometry)

    hame_other_area_trg_other_area_validate_polygon_geometry = PGTrigger(
        schema="hame",
        signature="trg_other_area_validate_polygon_geometry",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.other_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_validate_polygon_geometry()",
    )
    op.create_entity(hame_other_area_trg_other_area_validate_polygon_geometry)

    hame_land_use_area_trg_land_use_area_validate_polygon_geometry = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_validate_polygon_geometry",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.land_use_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_validate_polygon_geometry()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_validate_polygon_geometry)

    hame_line_trg_line_validate_geometry = PGTrigger(
        schema="hame",
        signature="trg_line_validate_geometry",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.line FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_line_validate_geometry()",
    )
    op.create_entity(hame_line_trg_line_validate_geometry)

    hame_plan_trg_plan_validate_polygon_geometry = PGTrigger(
        schema="hame",
        signature="trg_plan_validate_polygon_geometry",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.plan FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_validate_polygon_geometry()",
    )
    op.create_entity(hame_plan_trg_plan_validate_polygon_geometry)

    # ### end Alembic commands ###
