"""update triggers

Revision ID: b34254bbb1cc
Revises: 8f72c4abf6bd
Create Date: 2026-01-30 11:28:54.122421

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "b34254bbb1cc"
down_revision: str | None = "8f72c4abf6bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_modified_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            IF NEW IS DISTINCT FROM OLD THEN\n                NEW.modified_at = CURRENT_TIMESTAMP;\n                NEW.modifier = SESSION_USER;\n            END IF;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.replace_entity(hame_trgfunc_modified_at)

    hame_trgfunc_created_at = PGFunction(
        schema="hame",
        signature="trgfunc_created_at()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.created_at = CURRENT_TIMESTAMP;\n            NEW.creator = SESSION_USER;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.replace_entity(hame_trgfunc_created_at)

    hame_trgfunc_no_created_at_update = PGFunction(
        schema="hame",
        signature="trgfunc_no_created_at_update()",
        definition="RETURNS TRIGGER AS $$\n        BEGIN\n            NEW.created_at = OLD.created_at;\n            NEW.creator = OLD.creator;\n            return NEW;\n        END;\n        $$ language 'plpgsql'",
    )
    op.replace_entity(hame_trgfunc_no_created_at_update)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_no_created_at_update = PGFunction(
        schema="hame",
        signature="trgfunc_no_created_at_update()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            NEW.created_at = OLD.created_at;\n            return NEW;\n        END;\n        $function$",
    )
    op.replace_entity(hame_trgfunc_no_created_at_update)
    hame_trgfunc_created_at = PGFunction(
        schema="hame",
        signature="trgfunc_created_at()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            NEW.created_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $function$",
    )
    op.replace_entity(hame_trgfunc_created_at)
    hame_trgfunc_modified_at = PGFunction(
        schema="hame",
        signature="trgfunc_modified_at()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            NEW.modified_at = CURRENT_TIMESTAMP;\n            return NEW;\n        END;\n        $function$",
    )
    op.replace_entity(hame_trgfunc_modified_at)
    # ### end Alembic commands ###
