"""add plan locked field

Revision ID: f73abbd8c732
Revises: 7f5ef657d2d6
Create Date: 2026-01-09 07:49:25.292652

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f73abbd8c732"
down_revision: str | None = "7f5ef657d2d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plan",
        sa.Column("locked", sa.Boolean(), server_default="0", nullable=False),
        schema="hame",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plan", "locked", schema="hame")
    # ### end Alembic commands ###
