"""add plan cancellation info triggers

Revision ID: e8b9170673ed
Revises: 9e33c0721167
Create Date: 2026-09-07 20:29:58.574549

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "e8b9170673ed"
down_revision: str | None = "9e33c0721167"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_cancellation_info_trg_plan_cancellation_info_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_cancellation_info_modified_at",
        on_entity="hame.plan_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.plan_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(hame_plan_cancellation_info_trg_plan_cancellation_info_modified_at)

    hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_object_cancellation_info_modified_at",
        on_entity="hame.plan_object_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.plan_object_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(
        hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_modified_at
    )

    hame_cancelled_group_relation_trg_cancelled_group_relation_modified_at = PGTrigger(
        schema="hame",
        signature="trg_cancelled_group_relation_modified_at",
        on_entity="hame.cancelled_group_relation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.cancelled_group_relation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(
        hame_cancelled_group_relation_trg_cancelled_group_relation_modified_at
    )

    hame_plan_cancellation_info_trg_plan_cancellation_info_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_cancellation_info_created_at",
        on_entity="hame.plan_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_plan_cancellation_info_trg_plan_cancellation_info_created_at)

    hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_object_cancellation_info_created_at",
        on_entity="hame.plan_object_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_object_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_created_at
    )

    hame_cancelled_group_relation_trg_cancelled_group_relation_created_at = PGTrigger(
        schema="hame",
        signature="trg_cancelled_group_relation_created_at",
        on_entity="hame.cancelled_group_relation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.cancelled_group_relation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(
        hame_cancelled_group_relation_trg_cancelled_group_relation_created_at
    )

    hame_plan_cancellation_info_trg_plan_cancellation_info_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_cancellation_info_001_no_created_at_update",
        on_entity="hame.plan_cancellation_info",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        hame_plan_cancellation_info_trg_plan_cancellation_info_001_no_created_at_update
    )

    hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_object_cancellation_info_001_no_created_at_update",
        on_entity="hame.plan_object_cancellation_info",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_object_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_001_no_created_at_update
    )

    hame_cancelled_group_relation_trg_cancelled_group_relation_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_cancelled_group_relation_001_no_created_at_update",
        on_entity="hame.cancelled_group_relation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.cancelled_group_relation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(
        hame_cancelled_group_relation_trg_cancelled_group_relation_001_no_created_at_update
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_cancelled_group_relation_trg_cancelled_group_relation_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_cancelled_group_relation_001_no_created_at_update",
        on_entity="hame.cancelled_group_relation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.cancelled_group_relation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        hame_cancelled_group_relation_trg_cancelled_group_relation_001_no_created_at_update
    )

    hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_object_cancellation_info_001_no_created_at_update",
        on_entity="hame.plan_object_cancellation_info",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_object_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_001_no_created_at_update
    )

    hame_plan_cancellation_info_trg_plan_cancellation_info_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_plan_cancellation_info_001_no_created_at_update",
        on_entity="hame.plan_cancellation_info",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(
        hame_plan_cancellation_info_trg_plan_cancellation_info_001_no_created_at_update
    )

    hame_cancelled_group_relation_trg_cancelled_group_relation_created_at = PGTrigger(
        schema="hame",
        signature="trg_cancelled_group_relation_created_at",
        on_entity="hame.cancelled_group_relation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.cancelled_group_relation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        hame_cancelled_group_relation_trg_cancelled_group_relation_created_at
    )

    hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_object_cancellation_info_created_at",
        on_entity="hame.plan_object_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_object_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(
        hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_created_at
    )

    hame_plan_cancellation_info_trg_plan_cancellation_info_created_at = PGTrigger(
        schema="hame",
        signature="trg_plan_cancellation_info_created_at",
        on_entity="hame.plan_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_plan_cancellation_info_trg_plan_cancellation_info_created_at)

    hame_cancelled_group_relation_trg_cancelled_group_relation_modified_at = PGTrigger(
        schema="hame",
        signature="trg_cancelled_group_relation_modified_at",
        on_entity="hame.cancelled_group_relation",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.cancelled_group_relation\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(
        hame_cancelled_group_relation_trg_cancelled_group_relation_modified_at
    )

    hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_object_cancellation_info_modified_at",
        on_entity="hame.plan_object_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.plan_object_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(
        hame_plan_object_cancellation_info_trg_plan_object_cancellation_info_modified_at
    )

    hame_plan_cancellation_info_trg_plan_cancellation_info_modified_at = PGTrigger(
        schema="hame",
        signature="trg_plan_cancellation_info_modified_at",
        on_entity="hame.plan_cancellation_info",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.plan_cancellation_info\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(hame_plan_cancellation_info_trg_plan_cancellation_info_modified_at)

    # ### end Alembic commands ###
