"""add digital origin

Revision ID: 441bca104a11
Revises: 6a69d042ae3b
Create Date: 2026-09-01 11:45:46.053444

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "441bca104a11"
down_revision: str | None = "6a69d042ae3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "digital_origin",
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(), server_default="", nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("parent_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("creator", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column(
            "modified_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column("modifier", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["codes.digital_origin.id"],
            name="digital_origin_parent_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_digital_origin_level"),
        "digital_origin",
        ["level"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_digital_origin_parent_id"),
        "digital_origin",
        ["parent_id"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_digital_origin_short_name"),
        "digital_origin",
        ["short_name"],
        unique=False,
        schema="codes",
    )
    op.create_index(
        op.f("ix_codes_digital_origin_value"),
        "digital_origin",
        ["value"],
        unique=True,
        schema="codes",
    )
    op.execute(
        "GRANT SELECT ON codes.digital_origin TO arho_read_only, arho_read_write;"
    )
    # The koodistot loader only populates the code list later, so insert the code
    # that existing plan matters get here. The loader finds this row by its value and
    # updates the other fields.
    op.execute(
        """
        INSERT INTO codes.digital_origin (value, status, level, name)
        VALUES (
            '01',
            'VALID',
            1,
            '{"fin": "Tietomallin mukaan laadittu",
              "swe": "Utarbetad enligt en datamodell",
              "eng": "Prepared according to data model"}'::jsonb
        );
        """
    )
    # Add the column as nullable, set the code for existing plan matters, and only
    # then require a value.
    op.add_column(
        "plan_matter",
        sa.Column("digital_origin_id", sa.UUID(as_uuid=False), nullable=True),
        schema="hame",
    )
    op.execute(
        """
        UPDATE hame.plan_matter
        SET digital_origin_id = (
            SELECT id FROM codes.digital_origin WHERE value = '01'
        );
        """
    )
    op.alter_column("plan_matter", "digital_origin_id", nullable=False, schema="hame")
    op.create_foreign_key(
        "digital_origin_id_fkey",
        "plan_matter",
        "digital_origin",
        ["digital_origin_id"],
        ["id"],
        source_schema="hame",
        referent_schema="codes",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "digital_origin_id_fkey", "plan_matter", schema="hame", type_="foreignkey"
    )
    op.drop_column("plan_matter", "digital_origin_id", schema="hame")
    op.drop_index(
        op.f("ix_codes_digital_origin_value"),
        table_name="digital_origin",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_digital_origin_short_name"),
        table_name="digital_origin",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_digital_origin_parent_id"),
        table_name="digital_origin",
        schema="codes",
    )
    op.drop_index(
        op.f("ix_codes_digital_origin_level"),
        table_name="digital_origin",
        schema="codes",
    )
    op.drop_table("digital_origin", schema="codes")
    # ### end Alembic commands ###
