"""remove lifecycle update triggers

Revision ID: 108beab4d446
Revises: d83654421156
Create Date: 2026-05-20 16:37:30.242483

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "108beab4d446"
down_revision: str | None = "d83654421156"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_trg_point_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_point_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_point_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_point_update_lifecycle_status)

    hame_plan_trg_plan_plan_proposition_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_plan_proposition_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_plan_plan_proposition_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_plan_plan_proposition_update_lifecycle_status)

    hame_plan_trg_plan_plan_regulation_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_plan_regulation_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_plan_plan_regulation_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_plan_plan_regulation_update_lifecycle_status)

    hame_plan_trg_other_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_other_area_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_other_area_update_lifecycle_status)

    hame_plan_trg_line_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_line_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_line_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_line_update_lifecycle_status)

    hame_plan_trg_land_use_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_land_use_area_update_lifecycle_status()",
    )
    op.drop_entity(hame_plan_trg_land_use_area_update_lifecycle_status)

    hame_trgfunc_point_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_point_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.point\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.drop_entity(hame_trgfunc_point_update_lifecycle_status)

    hame_trgfunc_plan_plan_proposition_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_plan_proposition_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n            BEGIN\n                UPDATE hame.plan_proposition rt\n                SET lifecycle_status_id = NEW.lifecycle_status_id\n                WHERE\n                    EXISTS (\n                        SELECT 1\n                        FROM hame.plan_regulation_group prg\n                        WHERE\n                            prg.id = rt.plan_regulation_group_id\n                            AND prg.plan_id = NEW.id\n                    )\n                    AND lifecycle_status_id = OLD.lifecycle_status_id\n                ;\n                RETURN NEW;\n            END;\n            $function$",
    )
    op.drop_entity(hame_trgfunc_plan_plan_proposition_update_lifecycle_status)

    hame_trgfunc_plan_plan_regulation_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_plan_regulation_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n            BEGIN\n                UPDATE hame.plan_regulation rt\n                SET lifecycle_status_id = NEW.lifecycle_status_id\n                WHERE\n                    EXISTS (\n                        SELECT 1\n                        FROM hame.plan_regulation_group prg\n                        WHERE\n                            prg.id = rt.plan_regulation_group_id\n                            AND prg.plan_id = NEW.id\n                    )\n                    AND lifecycle_status_id = OLD.lifecycle_status_id\n                ;\n                RETURN NEW;\n            END;\n            $function$",
    )
    op.drop_entity(hame_trgfunc_plan_plan_regulation_update_lifecycle_status)

    hame_trgfunc_other_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.other_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.drop_entity(hame_trgfunc_other_area_update_lifecycle_status)

    hame_trgfunc_line_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_line_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.line\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.drop_entity(hame_trgfunc_line_update_lifecycle_status)

    hame_trgfunc_land_use_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.land_use_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.drop_entity(hame_trgfunc_land_use_area_update_lifecycle_status)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_trgfunc_land_use_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_land_use_area_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.land_use_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.create_entity(hame_trgfunc_land_use_area_update_lifecycle_status)

    hame_trgfunc_line_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_line_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.line\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.create_entity(hame_trgfunc_line_update_lifecycle_status)

    hame_trgfunc_other_area_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_other_area_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.other_area\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.create_entity(hame_trgfunc_other_area_update_lifecycle_status)

    hame_trgfunc_plan_plan_regulation_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_plan_regulation_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n            BEGIN\n                UPDATE hame.plan_regulation rt\n                SET lifecycle_status_id = NEW.lifecycle_status_id\n                WHERE\n                    EXISTS (\n                        SELECT 1\n                        FROM hame.plan_regulation_group prg\n                        WHERE\n                            prg.id = rt.plan_regulation_group_id\n                            AND prg.plan_id = NEW.id\n                    )\n                    AND lifecycle_status_id = OLD.lifecycle_status_id\n                ;\n                RETURN NEW;\n            END;\n            $function$",
    )
    op.create_entity(hame_trgfunc_plan_plan_regulation_update_lifecycle_status)

    hame_trgfunc_plan_plan_proposition_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_plan_plan_proposition_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n            BEGIN\n                UPDATE hame.plan_proposition rt\n                SET lifecycle_status_id = NEW.lifecycle_status_id\n                WHERE\n                    EXISTS (\n                        SELECT 1\n                        FROM hame.plan_regulation_group prg\n                        WHERE\n                            prg.id = rt.plan_regulation_group_id\n                            AND prg.plan_id = NEW.id\n                    )\n                    AND lifecycle_status_id = OLD.lifecycle_status_id\n                ;\n                RETURN NEW;\n            END;\n            $function$",
    )
    op.create_entity(hame_trgfunc_plan_plan_proposition_update_lifecycle_status)

    hame_trgfunc_point_update_lifecycle_status = PGFunction(
        schema="hame",
        signature="trgfunc_point_update_lifecycle_status()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n        BEGIN\n            UPDATE hame.point\n            SET lifecycle_status_id = NEW.lifecycle_status_id\n            WHERE (plan_id = NEW.id\n            AND lifecycle_status_id = OLD.lifecycle_status_id);\n            RETURN NEW;\n        END;\n        $function$",
    )
    op.create_entity(hame_trgfunc_point_update_lifecycle_status)

    hame_plan_trg_land_use_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_land_use_area_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_land_use_area_update_lifecycle_status)

    hame_plan_trg_line_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_line_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_line_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_line_update_lifecycle_status)

    hame_plan_trg_other_area_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_area_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_other_area_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_other_area_update_lifecycle_status)

    hame_plan_trg_plan_plan_regulation_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_plan_regulation_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_plan_plan_regulation_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_plan_plan_regulation_update_lifecycle_status)

    hame_plan_trg_plan_plan_proposition_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_plan_proposition_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_plan_plan_proposition_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_plan_plan_proposition_update_lifecycle_status)

    hame_plan_trg_point_update_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_point_update_lifecycle_status",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_point_update_lifecycle_status()",
    )
    op.create_entity(hame_plan_trg_point_update_lifecycle_status)

    # ### end Alembic commands ###
