"""set lifecycle only if null

Revision ID: 6a69d042ae3b
Revises: 108beab4d446
Create Date: 2026-05-22 08:58:07.455867

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "6a69d042ae3b"
down_revision: str | None = "108beab4d446"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_land_use_area_trg_land_use_area_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_new_lifecycle_status",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT ON land_use_area\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id IS NULL)\n        EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_land_use_area_trg_land_use_area_new_lifecycle_status)

    hame_line_trg_line_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_line_new_lifecycle_status",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT ON line\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id IS NULL)\n        EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_line_trg_line_new_lifecycle_status)

    hame_other_area_trg_other_area_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_area_new_lifecycle_status",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT ON other_area\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id IS NULL)\n        EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_other_area_trg_other_area_new_lifecycle_status)

    hame_point_trg_point_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_point_new_lifecycle_status",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE INSERT ON point\n        FOR EACH ROW\n        WHEN (NEW.lifecycle_status_id IS NULL)\n        EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_point_trg_point_new_lifecycle_status)

    hame_plan_regulation_trg_plan_regulation_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_new_lifecycle_status",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_regulation\n            FOR EACH ROW\n            WHEN (NEW.lifecycle_status_id IS NULL)\n            EXECUTE FUNCTION hame.trgfunc_plan_regulation_new_lifecycle_status()",
    )
    op.replace_entity(hame_plan_regulation_trg_plan_regulation_new_lifecycle_status)

    hame_plan_proposition_trg_plan_proposition_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_new_lifecycle_status",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_proposition\n            FOR EACH ROW\n            WHEN (NEW.lifecycle_status_id IS NULL)\n            EXECUTE FUNCTION hame.trgfunc_plan_regulation_new_lifecycle_status()",
    )
    op.replace_entity(hame_plan_proposition_trg_plan_proposition_new_lifecycle_status)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_proposition_trg_plan_proposition_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_new_lifecycle_status",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_proposition FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_plan_regulation_new_lifecycle_status()",
    )
    op.replace_entity(hame_plan_proposition_trg_plan_proposition_new_lifecycle_status)
    hame_plan_regulation_trg_plan_regulation_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_new_lifecycle_status",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.plan_regulation FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_plan_regulation_new_lifecycle_status()",
    )
    op.replace_entity(hame_plan_regulation_trg_plan_regulation_new_lifecycle_status)
    hame_point_trg_point_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_point_new_lifecycle_status",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.point FOR EACH ROW WHEN ((new.plan_id IS NOT NULL)) EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_point_trg_point_new_lifecycle_status)
    hame_other_area_trg_other_area_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_other_area_new_lifecycle_status",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.other_area FOR EACH ROW WHEN ((new.plan_id IS NOT NULL)) EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_other_area_trg_other_area_new_lifecycle_status)
    hame_line_trg_line_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_line_new_lifecycle_status",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.line FOR EACH ROW WHEN ((new.plan_id IS NOT NULL)) EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_line_trg_line_new_lifecycle_status)
    hame_land_use_area_trg_land_use_area_new_lifecycle_status = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_new_lifecycle_status",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.land_use_area FOR EACH ROW WHEN ((new.plan_id IS NOT NULL)) EXECUTE FUNCTION hame.trgfunc_plan_object_new_lifecycle_status()",
    )
    op.replace_entity(hame_land_use_area_trg_land_use_area_new_lifecycle_status)
    # ### end Alembic commands ###
