"""add plan cancellation info

Revision ID: 9e33c0721167
Revises: 8a0861aaf33a
Create Date: 2026-09-07 20:29:06.945531

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e33c0721167"
down_revision: str | None = "8a0861aaf33a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_cancellation_info",
        sa.Column(
            "plan_id",
            sa.UUID(as_uuid=False),
            nullable=False,
            comment="The plan that repeals the cancelled plan",
        ),
        sa.Column(
            "cancelled_plan_id",
            sa.UUID(as_uuid=False),
            nullable=False,
            comment="The plan that is repealed",
        ),
        sa.Column("cancels_entire_plan", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("creator", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column(
            "modified_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column("modifier", sa.String(), nullable=True),
        sa.CheckConstraint(
            "cancelled_plan_id <> plan_id",
            name="ck_plan_cancellation_info_cancelled_plan_id",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_plan_id"],
            ["hame.plan.id"],
            name="cancelled_plan_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["hame.plan.id"], name="plan_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_cancellation_info_cancelled_plan_id"),
        "plan_cancellation_info",
        ["cancelled_plan_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        "ix_plan_cancellation_info_plan_id_cancelled_plan_id",
        "plan_cancellation_info",
        ["plan_id", "cancelled_plan_id"],
        unique=True,
        schema="hame",
    )
    op.create_table(
        "cancelled_general_regulation_group_association",
        sa.Column("plan_cancellation_info_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("plan_regulation_group_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_cancellation_info_id"],
            ["hame.plan_cancellation_info.id"],
            name="plan_cancellation_info_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_regulation_group_id"],
            ["hame.plan_regulation_group.id"],
            name="plan_regulation_group_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint(
            "plan_cancellation_info_id", "plan_regulation_group_id"
        ),
        schema="hame",
    )
    op.create_index(
        "ix_cancelled_general_regulation_group_plan_regulation_group_id",
        "cancelled_general_regulation_group_association",
        ["plan_regulation_group_id"],
        unique=False,
        schema="hame",
    )
    op.create_table(
        "cancelled_group_relation",
        sa.Column("plan_cancellation_info_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("plan_regulation_group_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("creator", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column(
            "modified_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column("modifier", sa.String(), nullable=True),
        sa.Column("land_use_area_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("other_area_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("line_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("point_id", sa.UUID(as_uuid=False), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(land_use_area_id, other_area_id, line_id, point_id) = 1",
            name="ck_cancelled_group_relation_plan_object",
        ),
        sa.ForeignKeyConstraint(
            ["land_use_area_id"],
            ["hame.land_use_area.id"],
            name="land_use_area_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["hame.line.id"],
            name="line_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["other_area_id"],
            ["hame.other_area.id"],
            name="other_area_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["plan_cancellation_info_id"],
            ["hame.plan_cancellation_info.id"],
            name="plan_cancellation_info_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_regulation_group_id"],
            ["hame.plan_regulation_group.id"],
            name="plan_regulation_group_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["hame.point.id"],
            name="point_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_cancelled_group_relation_land_use_area_id"),
        "cancelled_group_relation",
        ["land_use_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_cancelled_group_relation_line_id"),
        "cancelled_group_relation",
        ["line_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_cancelled_group_relation_other_area_id"),
        "cancelled_group_relation",
        ["other_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_cancelled_group_relation_plan_cancellation_info_id"),
        "cancelled_group_relation",
        ["plan_cancellation_info_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_cancelled_group_relation_plan_regulation_group_id"),
        "cancelled_group_relation",
        ["plan_regulation_group_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_cancelled_group_relation_point_id"),
        "cancelled_group_relation",
        ["point_id"],
        unique=False,
        schema="hame",
    )
    op.create_table(
        "plan_object_cancellation_info",
        sa.Column("plan_cancellation_info_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("cancels_entire_plan_object", sa.Boolean(), nullable=False),
        sa.Column(
            "remaining_valid_geom_polygon",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=3067,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "remaining_valid_geom_line",
            geoalchemy2.types.Geometry(
                geometry_type="MULTILINESTRING",
                srid=3067,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "remaining_valid_geom_point",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOINT",
                srid=3067,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(as_uuid=False),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("creator", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column(
            "modified_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column("modifier", sa.String(), nullable=True),
        sa.Column("land_use_area_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("other_area_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("line_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("point_id", sa.UUID(as_uuid=False), nullable=True),
        sa.CheckConstraint(
            "(remaining_valid_geom_polygon is null or land_use_area_id is not null or other_area_id is not null) and (remaining_valid_geom_line is null or line_id is not null) and (remaining_valid_geom_point is null or point_id is not null)",
            name="ck_plan_object_cancellation_info_remaining_valid_geom_type",
        ),
        sa.CheckConstraint(
            "num_nonnulls(land_use_area_id, other_area_id, line_id, point_id) = 1",
            name="ck_plan_object_cancellation_info_plan_object",
        ),
        sa.CheckConstraint(
            "num_nonnulls(remaining_valid_geom_polygon, remaining_valid_geom_line, remaining_valid_geom_point) = case when cancels_entire_plan_object then 0 else 1 end",
            name="ck_plan_object_cancellation_info_remaining_valid_geom",
        ),
        sa.ForeignKeyConstraint(
            ["land_use_area_id"],
            ["hame.land_use_area.id"],
            name="land_use_area_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["hame.line.id"],
            name="line_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["other_area_id"],
            ["hame.other_area.id"],
            name="other_area_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["plan_cancellation_info_id"],
            ["hame.plan_cancellation_info.id"],
            name="plan_cancellation_info_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["hame.point.id"],
            name="point_id_fkey",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_object_cancellation_info_land_use_area_id"),
        "plan_object_cancellation_info",
        ["land_use_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_object_cancellation_info_line_id"),
        "plan_object_cancellation_info",
        ["line_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_object_cancellation_info_other_area_id"),
        "plan_object_cancellation_info",
        ["other_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_plan_object_cancellation_info_point_id"),
        "plan_object_cancellation_info",
        ["point_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        "ix_plan_object_cancellation_info_plan_cancellation_info_id",
        "plan_object_cancellation_info",
        ["plan_cancellation_info_id"],
        unique=False,
        schema="hame",
    )
    for table in (
        "plan_cancellation_info",
        "plan_object_cancellation_info",
        "cancelled_group_relation",
        "cancelled_general_regulation_group_association",
    ):
        op.execute(f"GRANT SELECT ON hame.{table} TO arho_read_only;")
        op.execute(
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON hame.{table} TO arho_read_write;"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_plan_object_cancellation_info_plan_cancellation_info_id",
        table_name="plan_object_cancellation_info",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_object_cancellation_info_point_id"),
        table_name="plan_object_cancellation_info",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_object_cancellation_info_other_area_id"),
        table_name="plan_object_cancellation_info",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_object_cancellation_info_line_id"),
        table_name="plan_object_cancellation_info",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_object_cancellation_info_land_use_area_id"),
        table_name="plan_object_cancellation_info",
        schema="hame",
    )
    op.drop_table("plan_object_cancellation_info", schema="hame")
    op.drop_index(
        op.f("ix_hame_cancelled_group_relation_point_id"),
        table_name="cancelled_group_relation",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_cancelled_group_relation_plan_regulation_group_id"),
        table_name="cancelled_group_relation",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_cancelled_group_relation_plan_cancellation_info_id"),
        table_name="cancelled_group_relation",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_cancelled_group_relation_other_area_id"),
        table_name="cancelled_group_relation",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_cancelled_group_relation_line_id"),
        table_name="cancelled_group_relation",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_cancelled_group_relation_land_use_area_id"),
        table_name="cancelled_group_relation",
        schema="hame",
    )
    op.drop_table("cancelled_group_relation", schema="hame")
    op.drop_index(
        "ix_cancelled_general_regulation_group_plan_regulation_group_id",
        table_name="cancelled_general_regulation_group_association",
        schema="hame",
    )
    op.drop_table("cancelled_general_regulation_group_association", schema="hame")
    op.drop_index(
        "ix_plan_cancellation_info_plan_id_cancelled_plan_id",
        table_name="plan_cancellation_info",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_plan_cancellation_info_cancelled_plan_id"),
        table_name="plan_cancellation_info",
        schema="hame",
    )
    op.drop_table("plan_cancellation_info", schema="hame")
    # ### end Alembic commands ###
