"""add digital origin triggers

Revision ID: 12e64d126240
Revises: 441bca104a11
Create Date: 2026-09-01 11:47:06.442788

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "12e64d126240"
down_revision: str | None = "441bca104a11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    codes_digital_origin_trg_digital_origin_modified_at = PGTrigger(
        schema="codes",
        signature="trg_digital_origin_modified_at",
        on_entity="codes.digital_origin",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON codes.digital_origin\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(codes_digital_origin_trg_digital_origin_modified_at)

    codes_digital_origin_trg_digital_origin_created_at = PGTrigger(
        schema="codes",
        signature="trg_digital_origin_created_at",
        on_entity="codes.digital_origin",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.digital_origin\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(codes_digital_origin_trg_digital_origin_created_at)

    codes_digital_origin_trg_digital_origin_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_digital_origin_001_no_created_at_update",
        on_entity="codes.digital_origin",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.digital_origin\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(codes_digital_origin_trg_digital_origin_001_no_created_at_update)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    codes_digital_origin_trg_digital_origin_001_no_created_at_update = PGTrigger(
        schema="codes",
        signature="trg_digital_origin_001_no_created_at_update",
        on_entity="codes.digital_origin",
        is_constraint=False,
        definition="BEFORE UPDATE ON codes.digital_origin\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(codes_digital_origin_trg_digital_origin_001_no_created_at_update)

    codes_digital_origin_trg_digital_origin_created_at = PGTrigger(
        schema="codes",
        signature="trg_digital_origin_created_at",
        on_entity="codes.digital_origin",
        is_constraint=False,
        definition="BEFORE INSERT ON codes.digital_origin\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(codes_digital_origin_trg_digital_origin_created_at)

    codes_digital_origin_trg_digital_origin_modified_at = PGTrigger(
        schema="codes",
        signature="trg_digital_origin_modified_at",
        on_entity="codes.digital_origin",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON codes.digital_origin\n        FOR EACH ROW\n        EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(codes_digital_origin_trg_digital_origin_modified_at)

    # ### end Alembic commands ###
