"""update views

Revision ID: 5c2431facab3
Revises: b34254bbb1cc
Create Date: 2026-01-30 11:42:42.995683

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_view import PGView
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "5c2431facab3"
down_revision: str | None = "b34254bbb1cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

tables = [
  "land_use_area_v",
  "line_v",
  "other_area_v",
  "point_v"
]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_land_use_area_v = PGView(
        schema="hame",
        signature="land_use_area_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    creator,\n    modified_at,\n    modifier,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('land_use_area', id) short_names,\n    hame.primary_use_regulations(id) primary_use,\n    hame.regulation_values('land_use_area', id) regulation_values\nfrom\n    hame.land_use_area",
    )
    op.replace_entity(hame_land_use_area_v)

    hame_other_area_v = PGView(
        schema="hame",
        signature="other_area_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    creator,\n    modified_at,\n    modifier,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('other_area', id) short_names,\n    hame.sub_area_regulations(id) sub_area,\n    hame.regulation_values('other_area', id) regulation_values\nfrom\n    hame.other_area",
    )
    op.replace_entity(hame_other_area_v)

    hame_line_v = PGView(
        schema="hame",
        signature="line_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    creator,\n    modified_at,\n    modifier,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('line', id) short_names,\n    hame.type_regulations('line', id) type_regulations,\n    hame.regulation_values('line', id) regulation_values\nfrom\n    hame.line",
    )
    op.replace_entity(hame_line_v)

    hame_point_v = PGView(
        schema="hame",
        signature="point_v",
        definition="select\n    id,\n    geom,\n    name,\n    source_data_object,\n    height_unit,\n    ordering,\n    type_of_underground_id,\n    plan_id,\n    exported_at,\n    lifecycle_status_id,\n    created_at,\n    creator,\n    modified_at,\n    modifier,\n    description,\n    height_min,\n    height_max,\n    height_reference_point,\n    period_of_validity_start,\n    period_of_validity_end,\n    hame.short_names('point', id) short_names,\n    hame.type_regulations('point', id) type_regulations,\n    hame.regulation_values('point', id) regulation_values\nfrom\n    hame.point",
    )
    op.replace_entity(hame_point_v)

    # ### commands auto generated by Alembic - please adjust! ###
    hame_land_use_area_v_trg_iiud_land_use_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_land_use_area_v",
        on_entity="hame.land_use_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.land_use_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_land_use_area_v_trg_iiud_land_use_area_v)

    hame_other_area_v_trg_iiud_other_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_other_area_v",
        on_entity="hame.other_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.other_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_other_area_v_trg_iiud_other_area_v)

    hame_point_v_trg_iiud_point_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_point_v",
        on_entity="hame.point_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.point_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_point_v_trg_iiud_point_v)

    hame_line_v_trg_iiud_line_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_line_v",
        on_entity="hame.line_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.line_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.create_entity(hame_line_v_trg_iiud_line_v)


    for table in tables:
        op.execute(f"GRANT SELECT ON hame.{table} TO arho_read_only;")
        op.execute(f"GRANT SELECT, INSERT, UPDATE ON hame.{table} TO arho_read_write;")
        op.execute(f"GRANT DELETE ON hame.{table} TO arho_read_write;")

def downgrade() -> None:

    for table in tables:
        op.execute(f"REVOKE SELECT ON hame.{table} FROM arho_read_only;")
        op.execute(f"REVOKE SELECT, INSERT, UPDATE ON hame.{table} FROM arho_read_write;")
        op.execute(f"REVOKE DELETE ON hame.{table} FROM arho_read_write;")


    hame_line_v_trg_iiud_line_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_line_v",
        on_entity="hame.line_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.line_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.drop_entity(hame_line_v_trg_iiud_line_v)

    hame_point_v_trg_iiud_point_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_point_v",
        on_entity="hame.point_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.point_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.drop_entity(hame_point_v_trg_iiud_point_v)

    hame_other_area_v_trg_iiud_other_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_other_area_v",
        on_entity="hame.other_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.other_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.drop_entity(hame_other_area_v_trg_iiud_other_area_v)

    hame_land_use_area_v_trg_iiud_land_use_area_v = PGTrigger(
        schema="hame",
        signature="trg_iiud_land_use_area_v",
        on_entity="hame.land_use_area_v",
        is_constraint=False,
        definition="INSTEAD OF INSERT OR UPDATE OR DELETE\nON hame.land_use_area_v\nFOR EACH ROW\nEXECUTE FUNCTION hame.trgf_iiud()",
    )
    op.drop_entity(hame_land_use_area_v_trg_iiud_land_use_area_v)

    hame_point_v = PGView(
        schema="hame",
        signature="point_v",
        definition="SELECT point.id,\n    point.geom,\n    point.name,\n    point.source_data_object,\n    point.height_unit,\n    point.ordering,\n    point.type_of_underground_id,\n    point.plan_id,\n    point.exported_at,\n    point.lifecycle_status_id,\n    point.created_at,\n    point.modified_at,\n    point.description,\n    point.height_min,\n    point.height_max,\n    point.height_reference_point,\n    point.period_of_validity_start,\n    point.period_of_validity_end,\n    hame.short_names('point'::text, point.id) AS short_names,\n    hame.type_regulations('point'::text, point.id) AS type_regulations,\n    hame.regulation_values('point'::text, point.id) AS regulation_values\n   FROM hame.point",
    )
    op.replace_entity(hame_point_v)
    hame_line_v = PGView(
        schema="hame",
        signature="line_v",
        definition="SELECT line.id,\n    line.geom,\n    line.name,\n    line.source_data_object,\n    line.height_unit,\n    line.ordering,\n    line.type_of_underground_id,\n    line.plan_id,\n    line.exported_at,\n    line.lifecycle_status_id,\n    line.created_at,\n    line.modified_at,\n    line.description,\n    line.height_min,\n    line.height_max,\n    line.height_reference_point,\n    line.period_of_validity_start,\n    line.period_of_validity_end,\n    hame.short_names('line'::text, line.id) AS short_names,\n    hame.type_regulations('line'::text, line.id) AS type_regulations,\n    hame.regulation_values('line'::text, line.id) AS regulation_values\n   FROM hame.line",
    )
    op.replace_entity(hame_line_v)
    hame_other_area_v = PGView(
        schema="hame",
        signature="other_area_v",
        definition="SELECT other_area.id,\n    other_area.geom,\n    other_area.name,\n    other_area.source_data_object,\n    other_area.height_unit,\n    other_area.ordering,\n    other_area.type_of_underground_id,\n    other_area.plan_id,\n    other_area.exported_at,\n    other_area.lifecycle_status_id,\n    other_area.created_at,\n    other_area.modified_at,\n    other_area.description,\n    other_area.height_min,\n    other_area.height_max,\n    other_area.height_reference_point,\n    other_area.period_of_validity_start,\n    other_area.period_of_validity_end,\n    hame.short_names('other_area'::text, other_area.id) AS short_names,\n    hame.sub_area_regulations(other_area.id) AS sub_area,\n    hame.regulation_values('other_area'::text, other_area.id) AS regulation_values\n   FROM hame.other_area",
    )
    op.replace_entity(hame_other_area_v)
    hame_land_use_area_v = PGView(
        schema="hame",
        signature="land_use_area_v",
        definition="SELECT land_use_area.id,\n    land_use_area.geom,\n    land_use_area.name,\n    land_use_area.source_data_object,\n    land_use_area.height_unit,\n    land_use_area.ordering,\n    land_use_area.type_of_underground_id,\n    land_use_area.plan_id,\n    land_use_area.exported_at,\n    land_use_area.lifecycle_status_id,\n    land_use_area.created_at,\n    land_use_area.modified_at,\n    land_use_area.description,\n    land_use_area.height_min,\n    land_use_area.height_max,\n    land_use_area.height_reference_point,\n    land_use_area.period_of_validity_start,\n    land_use_area.period_of_validity_end,\n    hame.short_names('land_use_area'::text, land_use_area.id) AS short_names,\n    hame.primary_use_regulations(land_use_area.id) AS primary_use,\n    hame.regulation_values('land_use_area'::text, land_use_area.id) AS regulation_values\n   FROM hame.land_use_area",
    )
    op.replace_entity(hame_land_use_area_v)
    # ### end Alembic commands ###
