"""add valid views

Revision ID: 82c89028a4d4
Revises: 12e64d126240
Create Date: 2026-09-02 08:45:21.879604

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = "82c89028a4d4"
down_revision: str | None = "12e64d126240"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

valid_views = [
    "plan_valid",
    "land_use_area_valid",
    "other_area_valid",
    "line_valid",
    "point_valid",
    "plan_regulation_group_valid",
    "plan_regulation_valid",
    "plan_proposition_valid",
    "additional_information_valid",
    "document_valid",
    "regulation_group_association_valid",
    "legal_effects_association_valid",
    "plan_theme_association_valid",
    "type_of_verbal_regulation_association_valid",
    "plan_matter_valid",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_valid = PGView(
        schema="hame",
        signature="plan_valid",
        definition="select\n    p.plan_matter_id,\n    p.name,\n    p.description,\n    p.scale,\n    p.official_use_only,\n    p.approval_date,\n    p.locked,\n    p.geom,\n    p.validated_at,\n    p.validation_errors,\n    p.exported_at,\n    p.id,\n    p.creator,\n    p.created_at,\n    p.modified_at,\n    p.modifier,\n    p.lifecycle_status_id,\n    p.period_of_validity_start,\n    p.period_of_validity_end\nfrom\n    hame.plan p\n    join codes.lifecycle_status ls on ls.id = p.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(p.period_of_validity_start, '-infinity'::date) and coalesce(p.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_plan_valid)

    hame_land_use_area_valid = PGView(
        schema="hame",
        signature="land_use_area_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.primary_use,\n    t.regulation_values\nfrom\n    hame.land_use_area_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_land_use_area_valid)

    hame_other_area_valid = PGView(
        schema="hame",
        signature="other_area_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.sub_area,\n    t.regulation_values\nfrom\n    hame.other_area_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_other_area_valid)

    hame_line_valid = PGView(
        schema="hame",
        signature="line_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.type_regulations,\n    t.regulation_values\nfrom\n    hame.line_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_line_valid)

    hame_point_valid = PGView(
        schema="hame",
        signature="point_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.type_regulations,\n    t.regulation_values\nfrom\n    hame.point_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_point_valid)

    hame_plan_regulation_group_valid = PGView(
        schema="hame",
        signature="plan_regulation_group_valid",
        definition="select\n    g.short_name,\n    g.name,\n    g.plan_id,\n    g.ordering,\n    g.type_of_plan_regulation_group_id,\n    g.id,\n    g.creator,\n    g.created_at,\n    g.modified_at,\n    g.modifier\nfrom\n    hame.plan_regulation_group g\n    join hame.plan_valid p on p.id = g.plan_id",
    )
    op.create_entity(hame_plan_regulation_group_valid)

    hame_plan_regulation_valid = PGView(
        schema="hame",
        signature="plan_regulation_valid",
        definition="select\n    r.plan_regulation_group_id,\nr.type_of_plan_regulation_id,\nr.ordering,\nr.subject_identifiers,\nr.exported_at,\nr.id,\nr.creator,\nr.created_at,\nr.modified_at,\nr.modifier,\nr.value_data_type,\nr.numeric_value,\nr.numeric_range_min,\nr.numeric_range_max,\nr.unit,\nr.text_value,\nr.text_syntax,\nr.code_list,\nr.code_value,\nr.code_title,\nr.height_reference_point,\nr.lifecycle_status_id,\nr.period_of_validity_start,\nr.period_of_validity_end\nfrom\n    hame.plan_regulation r\n    join hame.plan_regulation_group_valid g\n        on g.id = r.plan_regulation_group_id\n    join codes.lifecycle_status ls on ls.id = r.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(r.period_of_validity_start, '-infinity'::date) and coalesce(r.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_plan_regulation_valid)

    hame_plan_proposition_valid = PGView(
        schema="hame",
        signature="plan_proposition_valid",
        definition="select\n    r.plan_regulation_group_id,\nr.text_value,\nr.ordering,\nr.exported_at,\nr.id,\nr.creator,\nr.created_at,\nr.modified_at,\nr.modifier,\nr.lifecycle_status_id,\nr.period_of_validity_start,\nr.period_of_validity_end\nfrom\n    hame.plan_proposition r\n    join hame.plan_regulation_group_valid g\n        on g.id = r.plan_regulation_group_id\n    join codes.lifecycle_status ls on ls.id = r.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(r.period_of_validity_start, '-infinity'::date) and coalesce(r.period_of_validity_end, 'infinity'::date)",
    )
    op.create_entity(hame_plan_proposition_valid)

    hame_additional_information_valid = PGView(
        schema="hame",
        signature="additional_information_valid",
        definition="select\n    ai.plan_regulation_id,\n    ai.type_additional_information_id,\n    ai.id,\n    ai.creator,\n    ai.created_at,\n    ai.modified_at,\n    ai.modifier,\n    ai.value_data_type,\n    ai.numeric_value,\n    ai.numeric_range_min,\n    ai.numeric_range_max,\n    ai.unit,\n    ai.text_value,\n    ai.text_syntax,\n    ai.code_list,\n    ai.code_value,\n    ai.code_title,\n    ai.height_reference_point\nfrom\n    hame.additional_information ai\n    join hame.plan_regulation_valid r on r.id = ai.plan_regulation_id",
    )
    op.create_entity(hame_additional_information_valid)

    hame_document_valid = PGView(
        schema="hame",
        signature="document_valid",
        definition="select\n    d.type_of_document_id,\n    d.plan_id,\n    d.category_of_publicity_id,\n    d.personal_data_content_id,\n    d.retention_time_id,\n    d.language_id,\n    d.permanent_document_identifier,\n    d.name,\n    d.exported_at,\n    d.exported_file_key,\n    d.exported_file_etag,\n    d.arrival_date,\n    d.confirmation_date,\n    d.accessibility,\n    d.decision_date,\n    d.document_date,\n    d.url,\n    d.id,\n    d.creator,\n    d.created_at,\n    d.modified_at,\n    d.modifier\nfrom\n    hame.document d\n    join hame.plan_valid p on p.id = d.plan_id",
    )
    op.create_entity(hame_document_valid)

    hame_regulation_group_association_valid = PGView(
        schema="hame",
        signature="regulation_group_association_valid",
        definition="select\n    a.id,\n    a.plan_regulation_group_id,\n    a.plan_id,\n    a.land_use_area_id,\n    a.other_area_id,\n    a.line_id,\n    a.point_id\nfrom\n    hame.regulation_group_association a\n    join hame.plan_regulation_group_valid g\n        on g.id = a.plan_regulation_group_id\nwhere\n    exists (select 1 from hame.plan_valid p\n        where p.id = a.plan_id)\n    or exists (select 1 from hame.land_use_area_valid t\n        where t.id = a.land_use_area_id)\n    or exists (select 1 from hame.other_area_valid t\n        where t.id = a.other_area_id)\n    or exists (select 1 from hame.line_valid t\n        where t.id = a.line_id)\n    or exists (select 1 from hame.point_valid t\n        where t.id = a.point_id)",
    )
    op.create_entity(hame_regulation_group_association_valid)

    hame_legal_effects_association_valid = PGView(
        schema="hame",
        signature="legal_effects_association_valid",
        definition="select\n    a.plan_id,\n    a.legal_effects_of_master_plan_id\nfrom\n    hame.legal_effects_association a\n    join hame.plan_valid p on p.id = a.plan_id",
    )
    op.create_entity(hame_legal_effects_association_valid)

    hame_plan_theme_association_valid = PGView(
        schema="hame",
        signature="plan_theme_association_valid",
        definition="select\n    a.id,\n    a.plan_regulation_id,\n    a.plan_proposition_id,\n    a.plan_theme_id\nfrom\n    hame.plan_theme_association a\nwhere\n    exists (select 1 from hame.plan_regulation_valid r\n        where r.id = a.plan_regulation_id)\n    or exists (select 1 from hame.plan_proposition_valid pp\n        where pp.id = a.plan_proposition_id)",
    )
    op.create_entity(hame_plan_theme_association_valid)

    hame_type_of_verbal_regulation_association_valid = PGView(
        schema="hame",
        signature="type_of_verbal_regulation_association_valid",
        definition="select\n    a.plan_regulation_id,\n    a.type_of_verbal_plan_regulation_id\nfrom\n    hame.type_of_verbal_regulation_association a\n    join hame.plan_regulation_valid r on r.id = a.plan_regulation_id",
    )
    op.create_entity(hame_type_of_verbal_regulation_association_valid)

    hame_plan_matter_valid = PGView(
        schema="hame",
        signature="plan_matter_valid",
        definition="select\n    m.name,\n    m.description,\n    m.permanent_plan_identifier,\n    m.producers_plan_identifier,\n    m.case_identifier,\n    m.record_number,\n    m.digital_origin_id,\n    m.plan_type_id,\n    m.organisation_id,\n    m.id,\n    m.creator,\n    m.created_at,\n    m.modified_at,\n    m.modifier\nfrom\n    hame.plan_matter m\nwhere\n    exists (select 1 from hame.plan_valid p\n        where p.plan_matter_id = m.id)",
    )
    op.create_entity(hame_plan_matter_valid)

    # ### end Alembic commands ###

    # The valid views are read only: select for both roles, no insert, update
    # or delete. Dropping the views in downgrade also drops the grants.
    for view in valid_views:
        op.execute(f"GRANT SELECT ON hame.{view} TO arho_read_only;")
        op.execute(f"GRANT SELECT ON hame.{view} TO arho_read_write;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    hame_plan_matter_valid = PGView(
        schema="hame",
        signature="plan_matter_valid",
        definition="select\n    m.name,\n    m.description,\n    m.permanent_plan_identifier,\n    m.producers_plan_identifier,\n    m.case_identifier,\n    m.record_number,\n    m.digital_origin_id,\n    m.plan_type_id,\n    m.organisation_id,\n    m.id,\n    m.creator,\n    m.created_at,\n    m.modified_at,\n    m.modifier\nfrom\n    hame.plan_matter m\nwhere\n    exists (select 1 from hame.plan_valid p\n        where p.plan_matter_id = m.id)",
    )
    op.drop_entity(hame_plan_matter_valid)

    hame_type_of_verbal_regulation_association_valid = PGView(
        schema="hame",
        signature="type_of_verbal_regulation_association_valid",
        definition="select\n    a.plan_regulation_id,\n    a.type_of_verbal_plan_regulation_id\nfrom\n    hame.type_of_verbal_regulation_association a\n    join hame.plan_regulation_valid r on r.id = a.plan_regulation_id",
    )
    op.drop_entity(hame_type_of_verbal_regulation_association_valid)

    hame_plan_theme_association_valid = PGView(
        schema="hame",
        signature="plan_theme_association_valid",
        definition="select\n    a.id,\n    a.plan_regulation_id,\n    a.plan_proposition_id,\n    a.plan_theme_id\nfrom\n    hame.plan_theme_association a\nwhere\n    exists (select 1 from hame.plan_regulation_valid r\n        where r.id = a.plan_regulation_id)\n    or exists (select 1 from hame.plan_proposition_valid pp\n        where pp.id = a.plan_proposition_id)",
    )
    op.drop_entity(hame_plan_theme_association_valid)

    hame_legal_effects_association_valid = PGView(
        schema="hame",
        signature="legal_effects_association_valid",
        definition="select\n    a.plan_id,\n    a.legal_effects_of_master_plan_id\nfrom\n    hame.legal_effects_association a\n    join hame.plan_valid p on p.id = a.plan_id",
    )
    op.drop_entity(hame_legal_effects_association_valid)

    hame_regulation_group_association_valid = PGView(
        schema="hame",
        signature="regulation_group_association_valid",
        definition="select\n    a.id,\n    a.plan_regulation_group_id,\n    a.plan_id,\n    a.land_use_area_id,\n    a.other_area_id,\n    a.line_id,\n    a.point_id\nfrom\n    hame.regulation_group_association a\n    join hame.plan_regulation_group_valid g\n        on g.id = a.plan_regulation_group_id\nwhere\n    exists (select 1 from hame.plan_valid p\n        where p.id = a.plan_id)\n    or exists (select 1 from hame.land_use_area_valid t\n        where t.id = a.land_use_area_id)\n    or exists (select 1 from hame.other_area_valid t\n        where t.id = a.other_area_id)\n    or exists (select 1 from hame.line_valid t\n        where t.id = a.line_id)\n    or exists (select 1 from hame.point_valid t\n        where t.id = a.point_id)",
    )
    op.drop_entity(hame_regulation_group_association_valid)

    hame_document_valid = PGView(
        schema="hame",
        signature="document_valid",
        definition="select\n    d.type_of_document_id,\n    d.plan_id,\n    d.category_of_publicity_id,\n    d.personal_data_content_id,\n    d.retention_time_id,\n    d.language_id,\n    d.permanent_document_identifier,\n    d.name,\n    d.exported_at,\n    d.exported_file_key,\n    d.exported_file_etag,\n    d.arrival_date,\n    d.confirmation_date,\n    d.accessibility,\n    d.decision_date,\n    d.document_date,\n    d.url,\n    d.id,\n    d.creator,\n    d.created_at,\n    d.modified_at,\n    d.modifier\nfrom\n    hame.document d\n    join hame.plan_valid p on p.id = d.plan_id",
    )
    op.drop_entity(hame_document_valid)

    hame_additional_information_valid = PGView(
        schema="hame",
        signature="additional_information_valid",
        definition="select\n    ai.plan_regulation_id,\n    ai.type_additional_information_id,\n    ai.id,\n    ai.creator,\n    ai.created_at,\n    ai.modified_at,\n    ai.modifier,\n    ai.value_data_type,\n    ai.numeric_value,\n    ai.numeric_range_min,\n    ai.numeric_range_max,\n    ai.unit,\n    ai.text_value,\n    ai.text_syntax,\n    ai.code_list,\n    ai.code_value,\n    ai.code_title,\n    ai.height_reference_point\nfrom\n    hame.additional_information ai\n    join hame.plan_regulation_valid r on r.id = ai.plan_regulation_id",
    )
    op.drop_entity(hame_additional_information_valid)

    hame_plan_proposition_valid = PGView(
        schema="hame",
        signature="plan_proposition_valid",
        definition="select\n    r.plan_regulation_group_id,\nr.text_value,\nr.ordering,\nr.exported_at,\nr.id,\nr.creator,\nr.created_at,\nr.modified_at,\nr.modifier,\nr.lifecycle_status_id,\nr.period_of_validity_start,\nr.period_of_validity_end\nfrom\n    hame.plan_proposition r\n    join hame.plan_regulation_group_valid g\n        on g.id = r.plan_regulation_group_id\n    join codes.lifecycle_status ls on ls.id = r.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(r.period_of_validity_start, '-infinity'::date) and coalesce(r.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_plan_proposition_valid)

    hame_plan_regulation_valid = PGView(
        schema="hame",
        signature="plan_regulation_valid",
        definition="select\n    r.plan_regulation_group_id,\nr.type_of_plan_regulation_id,\nr.ordering,\nr.subject_identifiers,\nr.exported_at,\nr.id,\nr.creator,\nr.created_at,\nr.modified_at,\nr.modifier,\nr.value_data_type,\nr.numeric_value,\nr.numeric_range_min,\nr.numeric_range_max,\nr.unit,\nr.text_value,\nr.text_syntax,\nr.code_list,\nr.code_value,\nr.code_title,\nr.height_reference_point,\nr.lifecycle_status_id,\nr.period_of_validity_start,\nr.period_of_validity_end\nfrom\n    hame.plan_regulation r\n    join hame.plan_regulation_group_valid g\n        on g.id = r.plan_regulation_group_id\n    join codes.lifecycle_status ls on ls.id = r.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(r.period_of_validity_start, '-infinity'::date) and coalesce(r.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_plan_regulation_valid)

    hame_plan_regulation_group_valid = PGView(
        schema="hame",
        signature="plan_regulation_group_valid",
        definition="select\n    g.short_name,\n    g.name,\n    g.plan_id,\n    g.ordering,\n    g.type_of_plan_regulation_group_id,\n    g.id,\n    g.creator,\n    g.created_at,\n    g.modified_at,\n    g.modifier\nfrom\n    hame.plan_regulation_group g\n    join hame.plan_valid p on p.id = g.plan_id",
    )
    op.drop_entity(hame_plan_regulation_group_valid)

    hame_point_valid = PGView(
        schema="hame",
        signature="point_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.type_regulations,\n    t.regulation_values\nfrom\n    hame.point_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_point_valid)

    hame_line_valid = PGView(
        schema="hame",
        signature="line_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.type_regulations,\n    t.regulation_values\nfrom\n    hame.line_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_line_valid)

    hame_other_area_valid = PGView(
        schema="hame",
        signature="other_area_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.sub_area,\n    t.regulation_values\nfrom\n    hame.other_area_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_other_area_valid)

    hame_land_use_area_valid = PGView(
        schema="hame",
        signature="land_use_area_valid",
        definition="select\n    t.id,\n    t.geom,\n    t.name,\n    t.source_data_object,\n    t.height_unit,\n    t.ordering,\n    t.type_of_underground_id,\n    t.plan_id,\n    t.exported_at,\n    t.lifecycle_status_id,\n    t.created_at,\n    t.creator,\n    t.modified_at,\n    t.modifier,\n    t.description,\n    t.height_min,\n    t.height_max,\n    t.height_reference_point,\n    t.period_of_validity_start,\n    t.period_of_validity_end,\n    t.short_names,\n    t.primary_use,\n    t.regulation_values\nfrom\n    hame.land_use_area_v t\n    join hame.plan_valid p on p.id = t.plan_id\n    join codes.lifecycle_status ls on ls.id = t.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(t.period_of_validity_start, '-infinity'::date) and coalesce(t.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_land_use_area_valid)

    hame_plan_valid = PGView(
        schema="hame",
        signature="plan_valid",
        definition="select\n    p.plan_matter_id,\n    p.name,\n    p.description,\n    p.scale,\n    p.official_use_only,\n    p.approval_date,\n    p.locked,\n    p.geom,\n    p.validated_at,\n    p.validation_errors,\n    p.exported_at,\n    p.id,\n    p.creator,\n    p.created_at,\n    p.modified_at,\n    p.modifier,\n    p.lifecycle_status_id,\n    p.period_of_validity_start,\n    p.period_of_validity_end\nfrom\n    hame.plan p\n    join codes.lifecycle_status ls on ls.id = p.lifecycle_status_id\nwhere\n    ls.value = '13'\n    and current_date between coalesce(p.period_of_validity_start, '-infinity'::date) and coalesce(p.period_of_validity_end, 'infinity'::date)",
    )
    op.drop_entity(hame_plan_valid)

    # ### end Alembic commands ###
