"""Remove lifecycle history tables

Revision ID: d83654421156
Revises: 489b23cdab0a
Create Date: 2026-02-04 12:34:09.555102

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d83654421156"
down_revision: str | None = "489b23cdab0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    hame_event_date_trg_event_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_modified_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(hame_event_date_trg_event_date_modified_at)

    hame_lifecycle_date_trg_lifecycle_date_validate_dates = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_validate_dates",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_lifecycle_date_validate_dates()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_validate_dates)

    hame_event_date_trg_event_date_validate_dates = PGTrigger(
        schema="hame",
        signature="trg_event_date_validate_dates",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_event_date_validate_dates()",
    )
    op.drop_entity(hame_event_date_trg_event_date_validate_dates)

    hame_event_date_trg_event_date_validate_inside_status_date = PGTrigger(
        schema="hame",
        signature="trg_event_date_validate_inside_status_date",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_event_date_validate_inside_status_date()",
    )
    op.drop_entity(hame_event_date_trg_event_date_validate_inside_status_date)

    hame_event_date_trg_event_date_validate_type = PGTrigger(
        schema="hame",
        signature="trg_event_date_validate_type",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_event_date_validate_type()",
    )
    op.drop_entity(hame_event_date_trg_event_date_validate_type)

    hame_land_use_area_trg_new_land_use_area_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_land_use_area_add_lifecycle_date",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="AFTER INSERT ON hame.land_use_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_land_use_area_trg_new_land_use_area_add_lifecycle_date)

    hame_line_trg_new_line_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_line_add_lifecycle_date",
        on_entity="hame.line",
        is_constraint=False,
        definition="AFTER INSERT ON hame.line FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_line_trg_new_line_add_lifecycle_date)

    hame_other_area_trg_new_other_area_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_other_area_add_lifecycle_date",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="AFTER INSERT ON hame.other_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_other_area_trg_new_other_area_add_lifecycle_date)

    hame_plan_trg_new_plan_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_plan_add_lifecycle_date",
        on_entity="hame.plan",
        is_constraint=False,
        definition="AFTER INSERT ON hame.plan FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_plan_trg_new_plan_add_lifecycle_date)

    hame_plan_proposition_trg_new_plan_proposition_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_plan_proposition_add_lifecycle_date",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="AFTER INSERT ON hame.plan_proposition FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_plan_proposition_trg_new_plan_proposition_add_lifecycle_date)

    hame_plan_regulation_trg_new_plan_regulation_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_plan_regulation_add_lifecycle_date",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="AFTER INSERT ON hame.plan_regulation FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_plan_regulation_trg_new_plan_regulation_add_lifecycle_date)

    hame_land_use_area_trg_land_use_area_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_new_lifecycle_date",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.land_use_area FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_land_use_area_trg_land_use_area_new_lifecycle_date)

    hame_line_trg_line_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_line_new_lifecycle_date",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.line FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_line_trg_line_new_lifecycle_date)

    hame_other_area_trg_other_area_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_other_area_new_lifecycle_date",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.other_area FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_other_area_trg_other_area_new_lifecycle_date)

    hame_plan_trg_plan_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_new_lifecycle_date",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_plan_trg_plan_new_lifecycle_date)

    hame_plan_proposition_trg_plan_proposition_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_new_lifecycle_date",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_proposition FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_plan_proposition_trg_plan_proposition_new_lifecycle_date)

    hame_plan_regulation_trg_plan_regulation_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_new_lifecycle_date",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_regulation FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_plan_regulation_trg_plan_regulation_new_lifecycle_date)

    hame_point_trg_new_point_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_point_add_lifecycle_date",
        on_entity="hame.point",
        is_constraint=False,
        definition="AFTER INSERT ON hame.point FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.drop_entity(hame_point_trg_new_point_add_lifecycle_date)

    hame_point_trg_point_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_point_new_lifecycle_date",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.point FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.drop_entity(hame_point_trg_point_new_lifecycle_date)

    hame_lifecycle_date_trg_lifecycle_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_created_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_created_at)

    hame_event_date_trg_event_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_created_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.drop_entity(hame_event_date_trg_event_date_created_at)

    hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_001_no_created_at_update",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update)

    hame_event_date_trg_event_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_event_date_001_no_created_at_update",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.drop_entity(hame_event_date_trg_event_date_001_no_created_at_update)

    hame_trgfunc_lifecycle_date_validate_dates = PGFunction(
        schema="hame",
        signature="trgfunc_lifecycle_date_validate_dates()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF (\n            NEW.starting_at IS NOT NULL AND\n            NEW.ending_at IS NOT NULL AND\n            NEW.starting_at > NEW.ending_at\n        ) IS TRUE\n        THEN\n            RAISE EXCEPTION 'Status starting date % after ending date %',\n                NEW.starting_at, NEW.ending_at\n                USING HINT = 'Status ending date must be after starting date.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_lifecycle_date_validate_dates)

    hame_trgfunc_event_date_validate_dates = PGFunction(
        schema="hame",
        signature="trgfunc_event_date_validate_dates()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF (\n            NEW.starting_at IS NOT NULL AND\n            NEW.ending_at IS NOT NULL AND\n            NEW.starting_at > NEW.ending_at\n        ) IS TRUE\n        THEN\n            RAISE EXCEPTION 'Event starting date % after ending date %',\n                NEW.starting_at, NEW.ending_at\n                USING HINT = 'Event ending date must be after starting date.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_event_date_validate_dates)

    hame_trgfunc_event_date_validate_inside_status_date = PGFunction(
        schema="hame",
        signature="trgfunc_event_date_validate_inside_status_date()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        status_starting_at TIMESTAMP WITH TIME ZONE;\n        status_ending_at TIMESTAMP WITH TIME ZONE;\n    BEGIN\n        SELECT starting_at, ending_at INTO status_starting_at, status_ending_at\n        FROM hame.lifecycle_date\n        WHERE NEW.lifecycle_date_id = hame.lifecycle_date.id;\n        IF (\n            -- Does the event start before status starts?\n            (\n             NEW.starting_at < status_starting_at\n            ) OR\n            -- Missing event ending date means event is instantaneous. Only\n            -- events with ending date have a duration. Both must have ending\n            -- date specified to check if event ends after status ends.\n            (\n             NEW.ending_at IS NOT NULL AND status_ending_at IS NOT NULL AND\n             NEW.ending_at > status_ending_at\n            )\n        ) IS TRUE\n        THEN\n            RAISE EXCEPTION 'Event dates % - % outside status dates % - %',\n                NEW.starting_at, NEW.ending_at, status_starting_at, status_ending_at\n                USING HINT = 'Event cannot be outside lifecycle status dates.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_event_date_validate_inside_status_date)

    hame_trgfunc_event_date_validate_type = PGFunction(
        schema="hame",
        signature="trgfunc_event_date_validate_type()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        status_id UUID;\n        association_id UUID;\n    BEGIN\n        SELECT lifecycle_status_id INTO status_id\n        FROM\n            hame.lifecycle_date\n        WHERE\n            NEW.lifecycle_date_id = lifecycle_date.id;\n        SELECT id INTO association_id\n        FROM\n            codes.allowed_events\n        WHERE\n            lifecycle_status_id = status_id AND (\n                (NEW.decision_id IS NOT NULL AND\n                 name_of_plan_case_decision_id = NEW.decision_id) OR\n                (NEW.processing_event_id IS NOT NULL AND\n                 type_of_processing_event_id = NEW.processing_event_id) OR\n                (NEW.interaction_event_id IS NOT NULL AND\n                 type_of_interaction_event_id = NEW.interaction_event_id)\n            );\n        IF association_id IS NULL\n        THEN\n            RAISE EXCEPTION 'Wrong event type for status'\n            USING HINT = 'This event type cannot be added to this lifecycle status.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_event_date_validate_type)

    hame_trgfunc_new_object_add_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_new_object_add_lifecycle_date()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        EXECUTE format(\n            $query$\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, %I, starting_at)\n            VALUES\n                ($1, $2, CURRENT_TIMESTAMP)\n            $query$,\n            TG_TABLE_NAME || '_id'\n        ) USING NEW.lifecycle_status_id, NEW.id;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_new_object_add_lifecycle_date)

    hame_trgfunc_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_new_lifecycle_date()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        EXECUTE format(\n            $query$\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, %I, starting_at)\n            VALUES\n                ($1, $2, CURRENT_TIMESTAMP)\n            $query$,\n            TG_TABLE_NAME || '_id'\n        ) USING NEW.lifecycle_status_id, NEW.id;\n        EXECUTE format(\n            $query$\n            UPDATE hame.lifecycle_date\n            SET ending_at=CURRENT_TIMESTAMP\n            WHERE %I = $1\n                AND ending_at IS NULL\n                AND lifecycle_status_id = $2\n            $query$,\n            TG_TABLE_NAME || '_id'\n        ) USING NEW.id, OLD.lifecycle_status_id;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.drop_entity(hame_trgfunc_new_lifecycle_date)

    hame_lifecycle_date_trg_lifecycle_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_modified_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.drop_entity(hame_lifecycle_date_trg_lifecycle_date_modified_at)

    op.drop_index(
        op.f("ix_hame_event_date_lifecycle_date_id"),
        table_name="event_date",
        schema="hame",
    )
    op.drop_table("event_date", schema="hame")
    op.drop_index(
        op.f("ix_hame_lifecycle_date_land_use_area_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_lifecycle_status_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_line_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_other_area_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_plan_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_plan_proposition_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_plan_regulation_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_index(
        op.f("ix_hame_lifecycle_date_point_id"),
        table_name="lifecycle_date",
        schema="hame",
    )
    op.drop_table("lifecycle_date", schema="hame")



    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table(
        "lifecycle_date",
        sa.Column(
            "lifecycle_status_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("plan_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("plan_regulation_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("plan_proposition_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "starting_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ending_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("land_use_area_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("other_area_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("line_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("point_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("creator", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("modifier", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["land_use_area_id"],
            ["hame.land_use_area.id"],
            name="land_use_area_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lifecycle_status_id"],
            ["codes.lifecycle_status.id"],
            name="plan_lifecycle_status_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["hame.line.id"], name="line_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["other_area_id"],
            ["hame.other_area.id"],
            name="other_area_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["hame.plan.id"], name="plan_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["plan_proposition_id"],
            ["hame.plan_proposition.id"],
            name="plan_proposition_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_regulation_id"],
            ["hame.plan_regulation.id"],
            name="plan_regulation_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["point_id"], ["hame.point.id"], name="point_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="lifecycle_date_pkey"),
        schema="hame",
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_point_id"),
        "lifecycle_date",
        ["point_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_plan_regulation_id"),
        "lifecycle_date",
        ["plan_regulation_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_plan_proposition_id"),
        "lifecycle_date",
        ["plan_proposition_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_plan_id"),
        "lifecycle_date",
        ["plan_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_other_area_id"),
        "lifecycle_date",
        ["other_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_line_id"),
        "lifecycle_date",
        ["line_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_lifecycle_status_id"),
        "lifecycle_date",
        ["lifecycle_status_id"],
        unique=False,
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_lifecycle_date_land_use_area_id"),
        "lifecycle_date",
        ["land_use_area_id"],
        unique=False,
        schema="hame",
    )
    op.create_table(
        "event_date",
        sa.Column("lifecycle_date_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("decision_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("processing_event_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "interaction_event_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "starting_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ending_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "modified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("creator", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("modifier", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["codes.name_of_plan_case_decision.id"],
            name=op.f("name_of_plan_case_decision_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["interaction_event_id"],
            ["codes.type_of_interaction_event.id"],
            name=op.f("type_of_interaction_event_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["lifecycle_date_id"],
            ["hame.lifecycle_date.id"],
            name=op.f("lifecycle_date_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["processing_event_id"],
            ["codes.type_of_processing_event.id"],
            name=op.f("type_of_processing_event_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("event_date_pkey")),
        schema="hame",
    )
    op.create_index(
        op.f("ix_hame_event_date_lifecycle_date_id"),
        "event_date",
        ["lifecycle_date_id"],
        unique=False,
        schema="hame",
    )

    hame_trgfunc_new_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_new_lifecycle_date()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        EXECUTE format(\n            $query$\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, %I, starting_at)\n            VALUES\n                ($1, $2, CURRENT_TIMESTAMP)\n            $query$,\n            TG_TABLE_NAME || '_id'\n        ) USING NEW.lifecycle_status_id, NEW.id;\n        EXECUTE format(\n            $query$\n            UPDATE hame.lifecycle_date\n            SET ending_at=CURRENT_TIMESTAMP\n            WHERE %I = $1\n                AND ending_at IS NULL\n                AND lifecycle_status_id = $2\n            $query$,\n            TG_TABLE_NAME || '_id'\n        ) USING NEW.id, OLD.lifecycle_status_id;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_new_lifecycle_date)

    hame_trgfunc_new_object_add_lifecycle_date = PGFunction(
        schema="hame",
        signature="trgfunc_new_object_add_lifecycle_date()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        EXECUTE format(\n            $query$\n            INSERT INTO hame.lifecycle_date\n                (lifecycle_status_id, %I, starting_at)\n            VALUES\n                ($1, $2, CURRENT_TIMESTAMP)\n            $query$,\n            TG_TABLE_NAME || '_id'\n        ) USING NEW.lifecycle_status_id, NEW.id;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_new_object_add_lifecycle_date)

    hame_trgfunc_event_date_validate_type = PGFunction(
        schema="hame",
        signature="trgfunc_event_date_validate_type()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        status_id UUID;\n        association_id UUID;\n    BEGIN\n        SELECT lifecycle_status_id INTO status_id\n        FROM\n            hame.lifecycle_date\n        WHERE\n            NEW.lifecycle_date_id = lifecycle_date.id;\n        SELECT id INTO association_id\n        FROM\n            codes.allowed_events\n        WHERE\n            lifecycle_status_id = status_id AND (\n                (NEW.decision_id IS NOT NULL AND\n                 name_of_plan_case_decision_id = NEW.decision_id) OR\n                (NEW.processing_event_id IS NOT NULL AND\n                 type_of_processing_event_id = NEW.processing_event_id) OR\n                (NEW.interaction_event_id IS NOT NULL AND\n                 type_of_interaction_event_id = NEW.interaction_event_id)\n            );\n        IF association_id IS NULL\n        THEN\n            RAISE EXCEPTION 'Wrong event type for status'\n            USING HINT = 'This event type cannot be added to this lifecycle status.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_event_date_validate_type)

    hame_trgfunc_event_date_validate_inside_status_date = PGFunction(
        schema="hame",
        signature="trgfunc_event_date_validate_inside_status_date()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    DECLARE\n        status_starting_at TIMESTAMP WITH TIME ZONE;\n        status_ending_at TIMESTAMP WITH TIME ZONE;\n    BEGIN\n        SELECT starting_at, ending_at INTO status_starting_at, status_ending_at\n        FROM hame.lifecycle_date\n        WHERE NEW.lifecycle_date_id = hame.lifecycle_date.id;\n        IF (\n            -- Does the event start before status starts?\n            (\n             NEW.starting_at < status_starting_at\n            ) OR\n            -- Missing event ending date means event is instantaneous. Only\n            -- events with ending date have a duration. Both must have ending\n            -- date specified to check if event ends after status ends.\n            (\n             NEW.ending_at IS NOT NULL AND status_ending_at IS NOT NULL AND\n             NEW.ending_at > status_ending_at\n            )\n        ) IS TRUE\n        THEN\n            RAISE EXCEPTION 'Event dates % - % outside status dates % - %',\n                NEW.starting_at, NEW.ending_at, status_starting_at, status_ending_at\n                USING HINT = 'Event cannot be outside lifecycle status dates.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_event_date_validate_inside_status_date)

    hame_trgfunc_event_date_validate_dates = PGFunction(
        schema="hame",
        signature="trgfunc_event_date_validate_dates()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF (\n            NEW.starting_at IS NOT NULL AND\n            NEW.ending_at IS NOT NULL AND\n            NEW.starting_at > NEW.ending_at\n        ) IS TRUE\n        THEN\n            RAISE EXCEPTION 'Event starting date % after ending date %',\n                NEW.starting_at, NEW.ending_at\n                USING HINT = 'Event ending date must be after starting date.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_event_date_validate_dates)

    hame_trgfunc_lifecycle_date_validate_dates = PGFunction(
        schema="hame",
        signature="trgfunc_lifecycle_date_validate_dates()",
        definition="returns trigger\n LANGUAGE plpgsql\nAS $function$\n    BEGIN\n        IF (\n            NEW.starting_at IS NOT NULL AND\n            NEW.ending_at IS NOT NULL AND\n            NEW.starting_at > NEW.ending_at\n        ) IS TRUE\n        THEN\n            RAISE EXCEPTION 'Status starting date % after ending date %',\n                NEW.starting_at, NEW.ending_at\n                USING HINT = 'Status ending date must be after starting date.';\n        END IF;\n        RETURN NEW;\n    END;\n    $function$",
    )
    op.create_entity(hame_trgfunc_lifecycle_date_validate_dates)

    hame_event_date_trg_event_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_event_date_001_no_created_at_update",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_event_date_trg_event_date_001_no_created_at_update)

    hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_001_no_created_at_update",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_no_created_at_update()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_001_no_created_at_update)

    hame_event_date_trg_event_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_created_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_event_date_trg_event_date_created_at)

    hame_lifecycle_date_trg_lifecycle_date_created_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_created_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_created_at()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_created_at)

    hame_point_trg_point_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_point_new_lifecycle_date",
        on_entity="hame.point",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.point FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_point_trg_point_new_lifecycle_date)

    hame_point_trg_new_point_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_point_add_lifecycle_date",
        on_entity="hame.point",
        is_constraint=False,
        definition="AFTER INSERT ON hame.point FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_point_trg_new_point_add_lifecycle_date)

    hame_plan_regulation_trg_plan_regulation_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_regulation_new_lifecycle_date",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_regulation FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_plan_regulation_trg_plan_regulation_new_lifecycle_date)

    hame_plan_proposition_trg_plan_proposition_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_proposition_new_lifecycle_date",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan_proposition FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_plan_proposition_trg_plan_proposition_new_lifecycle_date)

    hame_plan_trg_plan_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_plan_new_lifecycle_date",
        on_entity="hame.plan",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.plan FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_plan_trg_plan_new_lifecycle_date)

    hame_other_area_trg_other_area_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_other_area_new_lifecycle_date",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.other_area FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_other_area_trg_other_area_new_lifecycle_date)

    hame_line_trg_line_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_line_new_lifecycle_date",
        on_entity="hame.line",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.line FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_line_trg_line_new_lifecycle_date)

    hame_land_use_area_trg_land_use_area_new_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_land_use_area_new_lifecycle_date",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="BEFORE UPDATE ON hame.land_use_area FOR EACH ROW WHEN ((new.lifecycle_status_id <> old.lifecycle_status_id)) EXECUTE FUNCTION hame.trgfunc_new_lifecycle_date()",
    )
    op.create_entity(hame_land_use_area_trg_land_use_area_new_lifecycle_date)

    hame_plan_regulation_trg_new_plan_regulation_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_plan_regulation_add_lifecycle_date",
        on_entity="hame.plan_regulation",
        is_constraint=False,
        definition="AFTER INSERT ON hame.plan_regulation FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_plan_regulation_trg_new_plan_regulation_add_lifecycle_date)

    hame_plan_proposition_trg_new_plan_proposition_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_plan_proposition_add_lifecycle_date",
        on_entity="hame.plan_proposition",
        is_constraint=False,
        definition="AFTER INSERT ON hame.plan_proposition FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_plan_proposition_trg_new_plan_proposition_add_lifecycle_date)

    hame_plan_trg_new_plan_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_plan_add_lifecycle_date",
        on_entity="hame.plan",
        is_constraint=False,
        definition="AFTER INSERT ON hame.plan FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_plan_trg_new_plan_add_lifecycle_date)

    hame_other_area_trg_new_other_area_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_other_area_add_lifecycle_date",
        on_entity="hame.other_area",
        is_constraint=False,
        definition="AFTER INSERT ON hame.other_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_other_area_trg_new_other_area_add_lifecycle_date)

    hame_line_trg_new_line_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_line_add_lifecycle_date",
        on_entity="hame.line",
        is_constraint=False,
        definition="AFTER INSERT ON hame.line FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_line_trg_new_line_add_lifecycle_date)

    hame_land_use_area_trg_new_land_use_area_add_lifecycle_date = PGTrigger(
        schema="hame",
        signature="trg_new_land_use_area_add_lifecycle_date",
        on_entity="hame.land_use_area",
        is_constraint=False,
        definition="AFTER INSERT ON hame.land_use_area FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_new_object_add_lifecycle_date()",
    )
    op.create_entity(hame_land_use_area_trg_new_land_use_area_add_lifecycle_date)

    hame_event_date_trg_event_date_validate_type = PGTrigger(
        schema="hame",
        signature="trg_event_date_validate_type",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_event_date_validate_type()",
    )
    op.create_entity(hame_event_date_trg_event_date_validate_type)

    hame_event_date_trg_event_date_validate_inside_status_date = PGTrigger(
        schema="hame",
        signature="trg_event_date_validate_inside_status_date",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_event_date_validate_inside_status_date()",
    )
    op.create_entity(hame_event_date_trg_event_date_validate_inside_status_date)

    hame_event_date_trg_event_date_validate_dates = PGTrigger(
        schema="hame",
        signature="trg_event_date_validate_dates",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_event_date_validate_dates()",
    )
    op.create_entity(hame_event_date_trg_event_date_validate_dates)

    hame_lifecycle_date_trg_lifecycle_date_validate_dates = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_validate_dates",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_lifecycle_date_validate_dates()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_validate_dates)

    hame_event_date_trg_event_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_event_date_modified_at",
        on_entity="hame.event_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.event_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(hame_event_date_trg_event_date_modified_at)

    hame_lifecycle_date_trg_lifecycle_date_modified_at = PGTrigger(
        schema="hame",
        signature="trg_lifecycle_date_modified_at",
        on_entity="hame.lifecycle_date",
        is_constraint=False,
        definition="BEFORE INSERT OR UPDATE ON hame.lifecycle_date FOR EACH ROW EXECUTE FUNCTION hame.trgfunc_modified_at()",
    )
    op.create_entity(hame_lifecycle_date_trg_lifecycle_date_modified_at)

    # ### end Alembic commands ###
