
name: Code-style

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  release:
    types: [published]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v2.0.3
