
name: Code-style

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "database/**"
      - "migrations/**"
      - "lambdas/**"
      - "test/**"
      - ".github/workflows/tests.yml"
  push:
    branches:
      - "main"
    paths:
      - "database/**"
      - "migrations/**"
      - "lambdas/**"
      - "test/**"
      - ".github/workflows/tests.yml"
  release:
    types: [published]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1
