name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: read

jobs:
  backport:
    name: Backport
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    if: >
      github.event.pull_request.merged
      && (
        (
          github.event.action == 'closed'
          && contains(join(github.event.pull_request.labels.*.name), 'backport')
        )
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport')
        )
      )
    steps:
      - name: Backport Bot
        id: backport

        uses: m-kuhn/backport@v1.2.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
